"""Checkpoint 3.2, engine side: rooms added in open space against an outside wall
(ADD_ROOM_OUTSIDE) and the derived insertion slots, on real CP2.2.1 plans (the web fixtures,
generated by the production solver from the benchmark corpus)."""

import json
from functools import cache
from pathlib import Path

import pytest

from p2b.core.vocabulary import (
    OpeningKind,
    OriginKind,
    PlanOpRejection,
    ProgrammeChange,
    RoomSide,
    RoomType,
)
from p2b.houseplans.engine import HousePlan, plan_geometry, sha256_of
from p2b.houseplans.engine.derive import analyse
from p2b.houseplans.engine.edit import BatchRejected, EditResult, apply_edit, edit
from p2b.houseplans.engine.graph_edit import Change, _rebuild, room_rects, side_line, touching
from p2b.houseplans.engine.insertion import InsertionSlot, insertion_slots
from p2b.houseplans.engine.intent import ArchitecturalIntent
from p2b.houseplans.engine.model import dump
from p2b.houseplans.engine.ops import AddRoomOutside, OperationRejected, RevertToRevision, apply
from tests.houseplans_support import benchmark_cases, intent_of, ruleset

WEB_FIXTURES = Path(__file__).resolve().parents[2] / "web" / "tests" / "fixtures" / "houseplans"
REVIEWED = (
    "1bhk_25x40_south_small",
    "2bhk_30x50_north_twowheeler_open",
    "2bhk_40x80_west_two_cars",
    "3bhk_45x70_two_cars_puja",
    "3bhk_50x60_wide_two_cars",
    "q06_4bhk_60x90_large_two_cars_puja_utility",
    "prop_very_wide_80x28",
    "1bhk_30x40_no_parking",
)
TYPES = (RoomType.WC, RoomType.UTILITY, RoomType.PUJA, RoomType.BEDROOM)


@cache
def plan_of(name: str) -> HousePlan:
    data = json.loads((WEB_FIXTURES / f"{name}.json").read_text("utf-8"))
    return HousePlan.model_validate(data["document"])


@cache
def intent_of_case(name: str) -> ArchitecturalIntent:
    return intent_of(benchmark_cases()[name], ruleset())


def run(name: str, op: AddRoomOutside, plan: HousePlan | None = None) -> EditResult:
    return edit(
        plan or plan_of(name),
        [op],
        ruleset(),
        intent=intent_of_case(name),
        ruleset_version=None,
        ruleset_sha256=None,
    )


def fitting_op(slot: InsertionSlot, room_type: RoomType) -> AddRoomOutside | None:
    """The smallest room of `room_type` the slot holds (clear minimums plus the walls, on the
    grid), or None when it does not fit: the check the editor makes before sending."""
    rule = ruleset().rooms[room_type]
    step = ruleset().grid_mm

    def up(v: int) -> int:
        return -(-v // step) * step

    depth = up(rule.min_short_mm + slot.depth_allowance_mm)
    clear_depth = depth - slot.depth_allowance_mm
    length = up(
        max(
            rule.min_short_mm + slot.length_allowance_mm,
            -(-rule.min_area_mm2 // clear_depth) + slot.length_allowance_mm,
        )
    )
    if depth > slot.max_depth_mm or length > slot.length_mm:
        return None
    return AddRoomOutside(
        host_room=slot.host_room,
        type=room_type,
        side=slot.side,
        offset_mm=slot.offset_mm,
        length_mm=length,
        depth_mm=depth,
    )


def accepted(name: str) -> list[tuple[AddRoomOutside, EditResult]]:
    out = []
    for slot in insertion_slots(plan_of(name), ruleset()):
        for room_type in TYPES:
            op = fitting_op(slot, room_type)
            if op is None:
                continue
            try:
                result = run(name, op)
            except BatchRejected:
                continue
            if result.report.valid:
                out.append((op, result))
    return out


def assert_canonical(plan: HousePlan) -> None:
    floor = plan.floors[0]
    rects = room_rects(floor)
    rebuilt = _rebuild(floor, rects, Change(rects=rects, rooms=list(floor.rooms)), ruleset())
    assert dump(rebuilt) == dump(floor)


# ---------- slots ----------


@pytest.mark.parametrize("name", REVIEWED)
def test_slots_are_deterministic_open_and_inside_the_buildable_area(name: str) -> None:
    plan = plan_of(name)
    slots = insertion_slots(plan, ruleset())
    assert slots == insertion_slots(plan_of(name), ruleset())
    rects = room_rects(plan.floors[0])
    o = ruleset().openings
    for slot in slots:
        assert slot.length_mm >= o.door_width_mm + 2 * o.jamb_clearance_mm
        assert slot.max_depth_mm > 0
        assert slot.open_area_kind in ("FORECOURT", "SIDE_YARD", "REAR_YARD", "COURT")
        op = AddRoomOutside(
            host_room=slot.host_room,
            type=RoomType.UTILITY,
            side=slot.side,
            offset_mm=slot.offset_mm,
            length_mm=slot.length_mm,
            depth_mm=slot.max_depth_mm,
        )
        # the whole slot at full depth never fails the placement checks (the validator may still
        # judge the room), and one millimetre deeper leaves the area or meets a room
        refusal = None
        try:
            apply(plan, op, ruleset())
        except OperationRejected as rejected:
            refusal = rejected.code
        assert refusal in (
            None,
            PlanOpRejection.HOSTED_ITEM_LEAVES_WALL,
            PlanOpRejection.HOSTED_ITEM_CHANGES_ROOMS,
        )
        deeper = op.model_copy(update={"depth_mm": slot.max_depth_mm + 1})
        with pytest.raises(OperationRejected) as caught:
            apply(plan, deeper, ruleset())
        assert caught.value.code in (
            PlanOpRejection.OUTSIDE_BUILDABLE_AREA,
            PlanOpRejection.ROOMS_WOULD_OVERLAP,
        )
        assert slot.host_room in rects


def test_a_plan_without_open_space_against_its_walls_offers_no_slot() -> None:
    assert insertion_slots(plan_of("1bhk_30x40_no_parking"), ruleset()) == []


# ---------- accepted insertions ----------


@pytest.mark.parametrize(
    "name",
    [
        "1bhk_25x40_south_small",
        "2bhk_30x50_north_twowheeler_open",
        "2bhk_40x80_west_two_cars",
        "3bhk_45x70_two_cars_puja",
        "3bhk_50x60_wide_two_cars",
        "q06_4bhk_60x90_large_two_cars_puja_utility",
        "prop_very_wide_80x28",
    ],
)
def test_a_room_added_in_open_space_is_valid_connected_and_recorded(name: str) -> None:
    plan = plan_of(name)
    hits = accepted(name)
    assert hits, f"no open-area room fits in {name}"
    op, result = hits[0]
    edited = result.plan
    before, after = room_rects(plan.floors[0]), room_rects(edited.floors[0])
    new = next(r for r in edited.floors[0].rooms if r.id not in before)
    # existing rooms untouched, the new one where asked, nothing overlapping
    assert {k: v for k, v in after.items() if k != new.id} == before
    keys = list(after)
    for i, a in enumerate(keys):
        for b in keys[i + 1 :]:
            assert after[a].overlap_area(after[b]) == 0
    assert new.type == op.type
    assert new.origin.kind == OriginKind.USER_EDIT
    assert_canonical(edited)
    # one door from the host; a window when the type needs one; the old openings unchanged
    links = {k: frozenset(v.connects) for k, v in analyse(edited).openings.items()}
    doors = [
        k
        for k, c in links.items()
        if c == {op.host_room, new.id}
        and next(o for o in edited.floors[0].openings if o.id == k).kind == OpeningKind.DOOR
    ]
    assert len(doors) == 1
    if ruleset().rooms[op.type].needs_window:
        assert any(
            new.id in c and "EXTERIOR" in c
            for k, c in links.items()
            if next(o for o in edited.floors[0].openings if o.id == k).kind == OpeningKind.WINDOW
        )
    old = {k: frozenset(v.connects) for k, v in analyse(plan).openings.items()}
    assert {k: links[k] for k in old} == old
    (record,) = edited.compromises
    assert record.change_key == ProgrammeChange.ROOM_ADDED_BY_OWNER
    assert record.params == {"room": new.id, "room_type": op.type.value}
    assert result.inverse == (RevertToRevision(revision=plan.meta.revision_no),)
    # deterministic, and the open areas recalculated: less open area by the room's footprint
    again, _ = apply_edit(plan, [op], ruleset())
    assert sha256_of(again.body()) == sha256_of(edited.body())
    open_before = sum(a.area_mm2 for a in plan_geometry(plan, ruleset()).floors[0].open_areas)
    open_after = sum(a.area_mm2 for a in plan_geometry(edited, ruleset()).floors[0].open_areas)
    assert open_before - open_after == after[new.id].area


def test_most_plans_with_open_space_take_several_kinds_of_room() -> None:
    counts = {name: len(accepted(name)) for name in REVIEWED}
    assert sum(1 for n in counts.values() if n > 0) >= 7
    assert sum(counts.values()) >= 20


# ---------- refusals ----------


def test_impossible_insertions_are_refused_with_a_reason() -> None:
    name = "3bhk_50x60_wide_two_cars"
    plan = plan_of(name)
    rules = ruleset()
    slot = insertion_slots(plan, rules)[0]
    rects = room_rects(plan.floors[0])
    base = AddRoomOutside(
        host_room=slot.host_room,
        type=RoomType.UTILITY,
        side=slot.side,
        offset_mm=slot.offset_mm,
        length_mm=slot.length_mm,
        depth_mm=min(slot.max_depth_mm, 1500),
    )
    # a side another room meets
    inner = next(
        (k, side, touching(rects, k, side)[0])
        for k in rects
        for side in RoomSide
        if k != "parking" and touching(rects, k, side)
    )
    _, lo, _ = side_line(rects[inner[0]], inner[1])
    cases: list[tuple[AddRoomOutside, PlanOpRejection]] = [
        (base.model_copy(update={"type": RoomType.PARKING}), PlanOpRejection.ROOM_TYPE_NOT_ALLOWED),
        (base.model_copy(update={"type": RoomType.STORE}), PlanOpRejection.ROOM_TYPE_NOT_ALLOWED),
        (
            base.model_copy(update={"offset_mm": slot.offset_mm + 1_000_000 - slot.length_mm}),
            PlanOpRejection.NOT_ON_OUTSIDE_WALL,
        ),
        (
            base.model_copy(
                update={
                    "host_room": inner[0],
                    "side": inner[1],
                    "offset_mm": inner[2][0] - lo,
                    "length_mm": inner[2][1] - inner[2][0],
                }
            ),
            PlanOpRejection.NOT_ON_OUTSIDE_WALL,
        ),
        (base.model_copy(update={"depth_mm": 900_000}), PlanOpRejection.OUTSIDE_BUILDABLE_AREA),
        (base.model_copy(update={"host_room": "parking"}), PlanOpRejection.NOT_ON_OUTSIDE_WALL),
    ]
    for op, code in cases:
        with pytest.raises(OperationRejected) as caught:
            apply(plan, op, rules)
        assert caught.value.code == code, op
    with pytest.raises(OperationRejected) as needs_rules:
        apply(plan, base)
    assert needs_rules.value.code == PlanOpRejection.NOT_SUPPORTED


def test_a_room_too_small_for_its_type_is_judged_by_the_validator_and_not_stored() -> None:
    name = "3bhk_50x60_wide_two_cars"
    slot = insertion_slots(plan_of(name), ruleset())[0]
    op = AddRoomOutside(
        host_room=slot.host_room,
        type=RoomType.BEDROOM,
        side=slot.side,
        offset_mm=slot.offset_mm,
        length_mm=ruleset().openings.door_width_mm + 2 * ruleset().openings.jamb_clearance_mm,
        depth_mm=min(slot.max_depth_mm, 1200),
    )
    result = run(name, op)
    assert not result.report.valid
    assert {e.code.value for e in result.report.errors} & {
        "ROOM_BELOW_MIN_AREA",
        "ROOM_BELOW_MIN_SHORT_SIDE",
    }


def test_a_door_needs_room_on_the_shared_wall() -> None:
    name = "3bhk_50x60_wide_two_cars"
    slot = insertion_slots(plan_of(name), ruleset())[0]
    op = AddRoomOutside(
        host_room=slot.host_room,
        type=RoomType.UTILITY,
        side=slot.side,
        offset_mm=slot.offset_mm,
        length_mm=ruleset().openings.door_width_mm,
        depth_mm=min(slot.max_depth_mm, 1500),
    )
    with pytest.raises(OperationRejected) as caught:
        apply(plan_of(name), op, ruleset())
    assert caught.value.code == PlanOpRejection.DOOR_DOES_NOT_FIT
