// Generated by apps/api/scripts/export_contracts.py from p2b/core/vocabulary.py.
// Do not edit by hand.

export const AudienceValues = ["ihb", "pro", "ops"] as const;
export type Audience = (typeof AudienceValues)[number];

export const UserStatusValues = ["PENDING_VERIFICATION", "ACTIVE", "SUSPENDED", "CLOSED"] as const;
export type UserStatus = (typeof UserStatusValues)[number];

export const ActorTypeValues = ["USER", "SYSTEM", "JOB"] as const;
export type ActorType = (typeof ActorTypeValues)[number];

export const SecuritySeverityValues = ["INFO", "WARNING", "CRITICAL"] as const;
export type SecuritySeverity = (typeof SecuritySeverityValues)[number];

export const ContactKindValues = ["EMAIL", "PHONE"] as const;
export type ContactKind = (typeof ContactKindValues)[number];

export const OtpPurposeValues = ["LOGIN", "ACCEPT_BUILD_PLAN", "SIGN_STRUCTURAL"] as const;
export type OtpPurpose = (typeof OtpPurposeValues)[number];

export const OtpStateValues = ["ISSUED", "VERIFIED", "EXPIRED", "LOCKED"] as const;
export type OtpState = (typeof OtpStateValues)[number];

export const FinishLevelValues = ["STANDARD", "PREMIUM", "LUXURY"] as const;
export type FinishLevel = (typeof FinishLevelValues)[number];

export const ProjectStatusValues = ["DRAFT", "SUBMITTED", "NEEDS_INFO", "ACCEPTED", "PLANNING", "PLAN_ISSUED", "SOURCING", "CONTRACTED", "BUILDING", "HANDOVER_PENDING", "COMPLETED", "ARCHIVED", "ON_HOLD", "CANCELLED"] as const;
export type ProjectStatus = (typeof ProjectStatusValues)[number];

export const ProjectTypeValues = ["NEW_HOME"] as const;
export type ProjectType = (typeof ProjectTypeValues)[number];

export const MembershipRoleValues = ["OWNER", "HOUSEHOLD", "CONTRACTOR", "ARCHITECT", "OPS_ADVISOR", "OPS_FIELD", "AUDITOR_ASSIGNED"] as const;
export type MembershipRole = (typeof MembershipRoleValues)[number];

export const ReviewFlagValues = ["PROPERTY_TYPE_OTHER", "CONSTRUCTION_STARTED"] as const;
export type ReviewFlag = (typeof ReviewFlagValues)[number];

export const EnquiryKindValues = ["COMING_SOON_HELP", "OTHER_CITY"] as const;
export type EnquiryKind = (typeof EnquiryKindValues)[number];

export const ComingSoonWorkValues = ["RENOVATION", "INTERIORS", "REPAIRS"] as const;
export type ComingSoonWork = (typeof ComingSoonWorkValues)[number];

export const FileStateValues = ["PENDING_UPLOAD", "UPLOADED", "SCANNING", "AVAILABLE", "QUARANTINED", "FAILED", "DELETED"] as const;
export type FileState = (typeof FileStateValues)[number];

export const FilePurposeValues = ["REQUIREMENT_UPLOAD", "AI_CONCEPT", "VERIFICATION_EVIDENCE", "PORTFOLIO", "INVOICE", "QUOTE_DOCUMENT", "DRAWING", "BUILD_PLAN_EVIDENCE", "BUILD_PLAN_DOCUMENT"] as const;
export type FilePurpose = (typeof FilePurposeValues)[number];

export const ConfigStatusValues = ["DRAFT", "ACTIVE", "RETIRED"] as const;
export type ConfigStatus = (typeof ConfigStatusValues)[number];

export const StageStateValues = ["NOT_STARTED", "IN_PROGRESS", "COMPLETION_REQUESTED", "COMPLETED", "BLOCKED", "ON_HOLD"] as const;
export type StageState = (typeof StageStateValues)[number];

export const GateStatusValues = ["NOT_INSPECTED", "SCHEDULED", "OPEN_NC", "CLEARED"] as const;
export type GateStatus = (typeof GateStatusValues)[number];

export const SpecLineStateValues = ["SPECIFIED", "OPTIONS_ISSUED", "CHOSEN", "PURCHASED", "INSTALLED", "VERIFIED"] as const;
export type SpecLineState = (typeof SpecLineStateValues)[number];

export const EngineerSignoffValues = ["PENDING", "SIGNED", "NOT_REQUIRED"] as const;
export type EngineerSignoff = (typeof EngineerSignoffValues)[number];

export const StaffRoleValues = ["OPS", "ADMIN"] as const;
export type StaffRole = (typeof StaffRoleValues)[number];

export const QueueKindValues = ["REQUIREMENT_REVIEW", "PROFESSIONAL_REVIEW"] as const;
export type QueueKind = (typeof QueueKindValues)[number];

export const QueueItemStateValues = ["OPEN", "CLAIMED", "RESOLVED"] as const;
export type QueueItemState = (typeof QueueItemStateValues)[number];

export const EstimateStatusValues = ["AVAILABLE", "UNAVAILABLE"] as const;
export type EstimateStatus = (typeof EstimateStatusValues)[number];

export const EstimateUnavailableReasonValues = ["BUILT_UP_AREA_NOT_GIVEN", "NO_RATE_CARD"] as const;
export type EstimateUnavailableReason = (typeof EstimateUnavailableReasonValues)[number];

export const PackageAvailabilityValues = ["NOT_SUBMITTED", "UNDER_REVIEW", "ELIGIBLE", "NOT_ELIGIBLE"] as const;
export type PackageAvailability = (typeof PackageAvailabilityValues)[number];

export const DesignViewValues = ["EXTERIOR", "INTERIOR"] as const;
export type DesignView = (typeof DesignViewValues)[number];

export const DesignGenerationStateValues = ["QUEUED", "RUNNING", "SUCCEEDED", "FAILED"] as const;
export type DesignGenerationState = (typeof DesignGenerationStateValues)[number];

export const DesignFundingValues = ["FREE", "PAID"] as const;
export type DesignFunding = (typeof DesignFundingValues)[number];

export const DesignFailureReasonValues = ["PROVIDER_UNAVAILABLE", "PROVIDER_TIMEOUT", "PROVIDER_REJECTED", "PROVIDER_ERROR", "INVALID_OUTPUT", "STALE"] as const;
export type DesignFailureReason = (typeof DesignFailureReasonValues)[number];

export const DesignBlockValues = ["NOT_SUBMITTED", "REQUIREMENT_BEING_UPDATED", "PROJECT_CLOSED", "FREE_QUOTA_USED", "ACCOUNT_DAILY_GENERATIONS", "ACCOUNT_DAILY_PROJECTS", "PROVIDER_NOT_CONFIGURED"] as const;
export type DesignBlock = (typeof DesignBlockValues)[number];

export const ListingStateValues = ["DRAFT", "PENDING_REVIEW", "CHANGES_REQUESTED", "LISTED", "REJECTED", "SUSPENDED"] as const;
export type ListingState = (typeof ListingStateValues)[number];

export const CheckKindValues = ["IDENTITY", "BUSINESS", "REGISTRATION", "PORTFOLIO", "REFERENCE", "SITE_VISIT"] as const;
export type CheckKind = (typeof CheckKindValues)[number];

export const CheckOutcomeValues = ["PASSED", "FAILED", "NOT_APPLICABLE"] as const;
export type CheckOutcome = (typeof CheckOutcomeValues)[number];

export const RequirementLevelValues = ["REQUIRED", "WHERE_APPLICABLE"] as const;
export type RequirementLevel = (typeof RequirementLevelValues)[number];

export const VerificationDecisionValues = ["APPROVED", "CHANGES_REQUESTED", "REJECTED"] as const;
export type VerificationDecision = (typeof VerificationDecisionValues)[number];

export const ProfessionalDocumentKindValues = ["IDENTITY", "BUSINESS", "REGISTRATION"] as const;
export type ProfessionalDocumentKind = (typeof ProfessionalDocumentKindValues)[number];

export const PortfolioReviewStateValues = ["PENDING", "APPROVED", "REJECTED"] as const;
export type PortfolioReviewState = (typeof PortfolioReviewStateValues)[number];

export const EligibilityOutcomeValues = ["PASSED", "FAILED"] as const;
export type EligibilityOutcome = (typeof EligibilityOutcomeValues)[number];

export const OfferingKindValues = ["PACKAGE", "AI_CREDIT"] as const;
export type OfferingKind = (typeof OfferingKindValues)[number];

export const PaymentModeValues = ["FULL", "INSTALMENTS"] as const;
export type PaymentMode = (typeof PaymentModeValues)[number];

export const DueRuleValues = ["ON_ORDER", "DAYS_AFTER_ACTIVATION"] as const;
export type DueRule = (typeof DueRuleValues)[number];

export const OrderStateValues = ["AWAITING_PAYMENT", "PART_PAID", "PAID", "CANCELLED", "PARTLY_REFUNDED", "REFUNDED"] as const;
export type OrderState = (typeof OrderStateValues)[number];

export const DueStateValues = ["DUE", "PAID", "CANCELLED"] as const;
export type DueState = (typeof DueStateValues)[number];

export const AttemptStateValues = ["CREATED", "CAPTURED", "FAILED", "EXPIRED"] as const;
export type AttemptState = (typeof AttemptStateValues)[number];

export const PackageStateValues = ["NOT_ACTIVE", "ACTIVE", "CANCELLED", "REFUNDED"] as const;
export type PackageState = (typeof PackageStateValues)[number];

export const CreditEntryValues = ["GRANT", "CONSUME", "RETURN", "REVOKE"] as const;
export type CreditEntry = (typeof CreditEntryValues)[number];

export const RefundRequestStateValues = ["REQUESTED", "APPROVED", "DECLINED", "REFUNDED", "FAILED"] as const;
export type RefundRequestState = (typeof RefundRequestStateValues)[number];

export const RefundStateValues = ["PROCESSING", "REFUNDED", "FAILED"] as const;
export type RefundState = (typeof RefundStateValues)[number];

export const InvoiceKindValues = ["TAX_INVOICE", "CREDIT_NOTE"] as const;
export type InvoiceKind = (typeof InvoiceKindValues)[number];

export const BillingExceptionKindValues = ["AMOUNT_MISMATCH", "UNKNOWN_ORDER", "DUPLICATE_CAPTURE", "CAPTURE_AFTER_CANCEL", "AUTHORISED_NOT_CAPTURED", "REFUND_MISMATCH"] as const;
export type BillingExceptionKind = (typeof BillingExceptionKindValues)[number];

export const BillingExceptionStateValues = ["OPEN", "RESOLVED"] as const;
export type BillingExceptionState = (typeof BillingExceptionStateValues)[number];

export const NeedStateValues = ["UNDECIDED", "NEEDED", "NOT_NEEDED"] as const;
export type NeedState = (typeof NeedStateValues)[number];

export const NeedSourceValues = ["REQUIREMENT", "FAMILY"] as const;
export type NeedSource = (typeof NeedSourceValues)[number];

export const EngagementPartyValues = ["LISTED", "OUTSIDE"] as const;
export type EngagementParty = (typeof EngagementPartyValues)[number];

export const EngagementStateValues = ["ACTIVE", "ENDED"] as const;
export type EngagementState = (typeof EngagementStateValues)[number];

export const ConnectionStateValues = ["SENT", "ACCEPTED", "DECLINED", "EXPIRED", "WITHDRAWN"] as const;
export type ConnectionState = (typeof ConnectionStateValues)[number];

export const DeclineReasonValues = ["UNAVAILABLE", "OUTSIDE_SERVICE_AREA", "SCOPE_MISMATCH", "SCHEDULE_MISMATCH", "COMPLIANCE", "ALREADY_ENGAGED", "OTHER"] as const;
export type DeclineReason = (typeof DeclineReasonValues)[number];

export const WithdrawReasonValues = ["FAMILY", "ANOTHER_ENGAGED", "PACKAGE_ENDED", "PROFESSIONAL_UNAVAILABLE", "PROJECT_CLOSED", "OPERATIONS"] as const;
export type WithdrawReason = (typeof WithdrawReasonValues)[number];

export const QuoteReviewStateValues = ["SUBMITTED"] as const;
export type QuoteReviewState = (typeof QuoteReviewStateValues)[number];

export const RateCardStatusValues = ["DRAFT", "PUBLISHED", "RETIRED"] as const;
export type RateCardStatus = (typeof RateCardStatusValues)[number];

export const DesignRequestKindValues = ["LISTED_PROFESSIONAL", "OUTSIDE_PROFESSIONAL", "HOMEOWNER_PROVIDED", "PLAN2BUILD_ARRANGED"] as const;
export type DesignRequestKind = (typeof DesignRequestKindValues)[number];

export const DrawingSetStateValues = ["DRAFT", "SUBMITTED", "IN_CHECK", "CHANGES_REQUESTED", "APPROVED", "REJECTED", "SUPERSEDED"] as const;
export type DrawingSetState = (typeof DrawingSetStateValues)[number];

export const DrawingClassValues = ["SITE_PLAN", "FLOOR_PLAN", "ELEVATION", "SECTION", "STRUCTURAL", "OTHER"] as const;
export type DrawingClass = (typeof DrawingClassValues)[number];

export const BuildPlanStateValues = ["DRAFT", "IN_REVIEW", "ISSUED", "ACCEPTED", "CHANGES_REQUESTED", "SUPERSEDED", "WITHDRAWN"] as const;
export type BuildPlanState = (typeof BuildPlanStateValues)[number];

export const ValueApplicabilityValues = ["APPLICABLE", "NOT_APPLICABLE"] as const;
export type ValueApplicability = (typeof ValueApplicabilityValues)[number];

export const ValueBasisValues = ["STRUCTURAL_DESIGN", "ARCHITECT_DRAWING", "HOMEOWNER_PROVIDED", "ADVISOR", "STANDARD_REFERENCE"] as const;
export type ValueBasis = (typeof ValueBasisValues)[number];

export const QuantityBasisValues = ["MEASURED_FROM_DRAWING", "PROVIDED_BY_PROFESSIONAL", "ADVISOR_ESTIMATE"] as const;
export type QuantityBasis = (typeof QuantityBasisValues)[number];

export const SignoffModeValues = ["ONE_TIME_CODE", "SIGNED_DOCUMENT"] as const;
export type SignoffMode = (typeof SignoffModeValues)[number];

export const SignerKindValues = ["LISTED", "OUTSIDE"] as const;
export type SignerKind = (typeof SignerKindValues)[number];

export const SignoffStateValues = ["SIGNED", "VOID"] as const;
export type SignoffState = (typeof SignoffStateValues)[number];
