// Generated by apps/api/scripts/export_contracts.py from p2b/core/vocabulary.py.
// Do not edit by hand.

export const AudienceValues = ["ihb", "pro", "ops"] as const;
export type Audience = (typeof AudienceValues)[number];

export const UserStatusValues = ["PENDING_VERIFICATION", "ACTIVE", "SUSPENDED", "CLOSED"] as const;
export type UserStatus = (typeof UserStatusValues)[number];

export const ActorTypeValues = ["USER", "SYSTEM", "JOB"] as const;
export type ActorType = (typeof ActorTypeValues)[number];

export const SecuritySeverityValues = ["INFO", "WARNING", "CRITICAL"] as const;
export type SecuritySeverity = (typeof SecuritySeverityValues)[number];

export const ContactKindValues = ["EMAIL", "PHONE"] as const;
export type ContactKind = (typeof ContactKindValues)[number];

export const OtpPurposeValues = ["LOGIN", "ACCEPT_BUILD_PLAN", "SIGN_STRUCTURAL", "SELECT_QUOTE", "SUBMIT_INSPECTION", "ACKNOWLEDGE_HANDOVER"] as const;
export type OtpPurpose = (typeof OtpPurposeValues)[number];

export const OtpStateValues = ["ISSUED", "VERIFIED", "EXPIRED", "LOCKED"] as const;
export type OtpState = (typeof OtpStateValues)[number];

export const FinishLevelValues = ["STANDARD", "PREMIUM", "LUXURY"] as const;
export type FinishLevel = (typeof FinishLevelValues)[number];

export const ProjectStatusValues = ["DRAFT", "SUBMITTED", "NEEDS_INFO", "ACCEPTED", "PLANNING", "PLAN_ISSUED", "SOURCING", "CONTRACTED", "BUILDING", "HANDOVER_PENDING", "COMPLETED", "ARCHIVED", "ON_HOLD", "CANCELLED"] as const;
export type ProjectStatus = (typeof ProjectStatusValues)[number];

export const ProjectTypeValues = ["NEW_HOME"] as const;
export type ProjectType = (typeof ProjectTypeValues)[number];

export const MembershipRoleValues = ["OWNER", "HOUSEHOLD", "CONTRACTOR", "ARCHITECT", "OPS_ADVISOR", "OPS_FIELD", "AUDITOR_ASSIGNED"] as const;
export type MembershipRole = (typeof MembershipRoleValues)[number];

export const ReviewFlagValues = ["PROPERTY_TYPE_OTHER", "CONSTRUCTION_STARTED"] as const;
export type ReviewFlag = (typeof ReviewFlagValues)[number];

export const EnquiryKindValues = ["COMING_SOON_HELP", "OTHER_CITY"] as const;
export type EnquiryKind = (typeof EnquiryKindValues)[number];

export const ComingSoonWorkValues = ["RENOVATION", "INTERIORS", "REPAIRS"] as const;
export type ComingSoonWork = (typeof ComingSoonWorkValues)[number];

export const FileStateValues = ["PENDING_UPLOAD", "UPLOADED", "SCANNING", "AVAILABLE", "QUARANTINED", "FAILED", "DELETED"] as const;
export type FileState = (typeof FileStateValues)[number];

export const FilePurposeValues = ["REQUIREMENT_UPLOAD", "AI_CONCEPT", "VERIFICATION_EVIDENCE", "PORTFOLIO", "INVOICE", "QUOTE_DOCUMENT", "DRAWING", "BUILD_PLAN_EVIDENCE", "BUILD_PLAN_DOCUMENT", "QUOTE_ATTACHMENT", "COMPARISON_DOCUMENT", "STAGE_EVIDENCE", "INSPECTION_EVIDENCE", "INSPECTION_REPORT", "HANDOVER_DOCUMENT", "BUILD_RECORD_DOCUMENT", "BUILD_RECORD_EXPORT"] as const;
export type FilePurpose = (typeof FilePurposeValues)[number];

export const ConfigStatusValues = ["DRAFT", "ACTIVE", "RETIRED"] as const;
export type ConfigStatus = (typeof ConfigStatusValues)[number];

export const StageStateValues = ["NOT_STARTED", "IN_PROGRESS", "COMPLETION_REQUESTED", "COMPLETED", "BLOCKED", "ON_HOLD"] as const;
export type StageState = (typeof StageStateValues)[number];

export const GateStatusValues = ["NOT_INSPECTED", "SCHEDULED", "OPEN_NC", "CLEARED"] as const;
export type GateStatus = (typeof GateStatusValues)[number];

export const SpecLineStateValues = ["SPECIFIED", "OPTIONS_ISSUED", "CHOSEN", "PURCHASED", "INSTALLED", "VERIFIED"] as const;
export type SpecLineState = (typeof SpecLineStateValues)[number];

export const EngineerSignoffValues = ["PENDING", "SIGNED", "NOT_REQUIRED"] as const;
export type EngineerSignoff = (typeof EngineerSignoffValues)[number];

export const StaffRoleValues = ["OPS", "ADMIN"] as const;
export type StaffRole = (typeof StaffRoleValues)[number];

export const QueueKindValues = ["REQUIREMENT_REVIEW", "PROFESSIONAL_REVIEW"] as const;
export type QueueKind = (typeof QueueKindValues)[number];

export const QueueItemStateValues = ["OPEN", "CLAIMED", "RESOLVED"] as const;
export type QueueItemState = (typeof QueueItemStateValues)[number];

export const EstimateStatusValues = ["AVAILABLE", "UNAVAILABLE"] as const;
export type EstimateStatus = (typeof EstimateStatusValues)[number];

export const EstimateUnavailableReasonValues = ["BUILT_UP_AREA_NOT_GIVEN", "NO_RATE_CARD"] as const;
export type EstimateUnavailableReason = (typeof EstimateUnavailableReasonValues)[number];

export const PackageAvailabilityValues = ["NOT_SUBMITTED", "UNDER_REVIEW", "ELIGIBLE", "NOT_ELIGIBLE"] as const;
export type PackageAvailability = (typeof PackageAvailabilityValues)[number];

export const DesignViewValues = ["EXTERIOR", "INTERIOR"] as const;
export type DesignView = (typeof DesignViewValues)[number];

export const DesignGenerationStateValues = ["QUEUED", "RUNNING", "SUCCEEDED", "FAILED"] as const;
export type DesignGenerationState = (typeof DesignGenerationStateValues)[number];

export const DesignFundingValues = ["FREE", "PAID"] as const;
export type DesignFunding = (typeof DesignFundingValues)[number];

export const DesignFailureReasonValues = ["PROVIDER_UNAVAILABLE", "PROVIDER_TIMEOUT", "PROVIDER_REJECTED", "PROVIDER_ERROR", "INVALID_OUTPUT", "STALE"] as const;
export type DesignFailureReason = (typeof DesignFailureReasonValues)[number];

export const DesignBlockValues = ["NOT_SUBMITTED", "REQUIREMENT_BEING_UPDATED", "PROJECT_CLOSED", "FREE_QUOTA_USED", "ACCOUNT_DAILY_GENERATIONS", "ACCOUNT_DAILY_PROJECTS", "PROVIDER_NOT_CONFIGURED"] as const;
export type DesignBlock = (typeof DesignBlockValues)[number];

export const ListingStateValues = ["DRAFT", "PENDING_REVIEW", "CHANGES_REQUESTED", "LISTED", "REJECTED", "SUSPENDED"] as const;
export type ListingState = (typeof ListingStateValues)[number];

export const CheckKindValues = ["IDENTITY", "BUSINESS", "REGISTRATION", "PORTFOLIO", "REFERENCE", "SITE_VISIT"] as const;
export type CheckKind = (typeof CheckKindValues)[number];

export const CheckOutcomeValues = ["PASSED", "FAILED", "NOT_APPLICABLE"] as const;
export type CheckOutcome = (typeof CheckOutcomeValues)[number];

export const RequirementLevelValues = ["REQUIRED", "WHERE_APPLICABLE"] as const;
export type RequirementLevel = (typeof RequirementLevelValues)[number];

export const VerificationDecisionValues = ["APPROVED", "CHANGES_REQUESTED", "REJECTED"] as const;
export type VerificationDecision = (typeof VerificationDecisionValues)[number];

export const ProfessionalDocumentKindValues = ["IDENTITY", "BUSINESS", "REGISTRATION"] as const;
export type ProfessionalDocumentKind = (typeof ProfessionalDocumentKindValues)[number];

export const PortfolioReviewStateValues = ["PENDING", "APPROVED", "REJECTED"] as const;
export type PortfolioReviewState = (typeof PortfolioReviewStateValues)[number];

export const EligibilityOutcomeValues = ["PASSED", "FAILED"] as const;
export type EligibilityOutcome = (typeof EligibilityOutcomeValues)[number];

export const OfferingKindValues = ["PACKAGE", "AI_CREDIT"] as const;
export type OfferingKind = (typeof OfferingKindValues)[number];

export const PaymentModeValues = ["FULL", "INSTALMENTS"] as const;
export type PaymentMode = (typeof PaymentModeValues)[number];

export const DueRuleValues = ["ON_ORDER", "DAYS_AFTER_ACTIVATION"] as const;
export type DueRule = (typeof DueRuleValues)[number];

export const OrderStateValues = ["AWAITING_PAYMENT", "PART_PAID", "PAID", "CANCELLED", "PARTLY_REFUNDED", "REFUNDED"] as const;
export type OrderState = (typeof OrderStateValues)[number];

export const DueStateValues = ["DUE", "PAID", "CANCELLED"] as const;
export type DueState = (typeof DueStateValues)[number];

export const AttemptStateValues = ["CREATED", "CAPTURED", "FAILED", "EXPIRED"] as const;
export type AttemptState = (typeof AttemptStateValues)[number];

export const PackageStateValues = ["NOT_ACTIVE", "ACTIVE", "CANCELLED", "REFUNDED"] as const;
export type PackageState = (typeof PackageStateValues)[number];

export const CreditEntryValues = ["GRANT", "CONSUME", "RETURN", "REVOKE"] as const;
export type CreditEntry = (typeof CreditEntryValues)[number];

export const RefundRequestStateValues = ["REQUESTED", "APPROVED", "DECLINED", "REFUNDED", "FAILED"] as const;
export type RefundRequestState = (typeof RefundRequestStateValues)[number];

export const RefundStateValues = ["PROCESSING", "REFUNDED", "FAILED"] as const;
export type RefundState = (typeof RefundStateValues)[number];

export const InvoiceKindValues = ["TAX_INVOICE", "CREDIT_NOTE"] as const;
export type InvoiceKind = (typeof InvoiceKindValues)[number];

export const BillingExceptionKindValues = ["AMOUNT_MISMATCH", "UNKNOWN_ORDER", "DUPLICATE_CAPTURE", "CAPTURE_AFTER_CANCEL", "AUTHORISED_NOT_CAPTURED", "REFUND_MISMATCH"] as const;
export type BillingExceptionKind = (typeof BillingExceptionKindValues)[number];

export const BillingExceptionStateValues = ["OPEN", "RESOLVED"] as const;
export type BillingExceptionState = (typeof BillingExceptionStateValues)[number];

export const NeedStateValues = ["UNDECIDED", "NEEDED", "NOT_NEEDED"] as const;
export type NeedState = (typeof NeedStateValues)[number];

export const NeedSourceValues = ["REQUIREMENT", "FAMILY"] as const;
export type NeedSource = (typeof NeedSourceValues)[number];

export const EngagementPartyValues = ["LISTED", "OUTSIDE"] as const;
export type EngagementParty = (typeof EngagementPartyValues)[number];

export const EngagementStateValues = ["ACTIVE", "ENDED"] as const;
export type EngagementState = (typeof EngagementStateValues)[number];

export const ConnectionStateValues = ["SENT", "ACCEPTED", "DECLINED", "EXPIRED", "WITHDRAWN"] as const;
export type ConnectionState = (typeof ConnectionStateValues)[number];

export const DeclineReasonValues = ["UNAVAILABLE", "OUTSIDE_SERVICE_AREA", "SCOPE_MISMATCH", "SCHEDULE_MISMATCH", "COMPLIANCE", "ALREADY_ENGAGED", "OTHER"] as const;
export type DeclineReason = (typeof DeclineReasonValues)[number];

export const WithdrawReasonValues = ["FAMILY", "ANOTHER_ENGAGED", "PACKAGE_ENDED", "PROFESSIONAL_UNAVAILABLE", "PROJECT_CLOSED", "OPERATIONS"] as const;
export type WithdrawReason = (typeof WithdrawReasonValues)[number];

export const QuoteReviewStateValues = ["SUBMITTED"] as const;
export type QuoteReviewState = (typeof QuoteReviewStateValues)[number];

export const RateCardStatusValues = ["DRAFT", "PUBLISHED", "RETIRED"] as const;
export type RateCardStatus = (typeof RateCardStatusValues)[number];

export const DesignRequestKindValues = ["LISTED_PROFESSIONAL", "OUTSIDE_PROFESSIONAL", "HOMEOWNER_PROVIDED", "PLAN2BUILD_ARRANGED"] as const;
export type DesignRequestKind = (typeof DesignRequestKindValues)[number];

export const DrawingSetStateValues = ["DRAFT", "SUBMITTED", "IN_CHECK", "CHANGES_REQUESTED", "APPROVED", "REJECTED", "SUPERSEDED"] as const;
export type DrawingSetState = (typeof DrawingSetStateValues)[number];

export const DrawingClassValues = ["SITE_PLAN", "FLOOR_PLAN", "ELEVATION", "SECTION", "STRUCTURAL", "OTHER"] as const;
export type DrawingClass = (typeof DrawingClassValues)[number];

export const BuildPlanStateValues = ["DRAFT", "IN_REVIEW", "ISSUED", "ACCEPTED", "CHANGES_REQUESTED", "SUPERSEDED", "WITHDRAWN"] as const;
export type BuildPlanState = (typeof BuildPlanStateValues)[number];

export const ValueApplicabilityValues = ["APPLICABLE", "NOT_APPLICABLE"] as const;
export type ValueApplicability = (typeof ValueApplicabilityValues)[number];

export const ValueBasisValues = ["STRUCTURAL_DESIGN", "ARCHITECT_DRAWING", "HOMEOWNER_PROVIDED", "ADVISOR", "STANDARD_REFERENCE"] as const;
export type ValueBasis = (typeof ValueBasisValues)[number];

export const QuantityBasisValues = ["MEASURED_FROM_DRAWING", "PROVIDED_BY_PROFESSIONAL", "ADVISOR_ESTIMATE"] as const;
export type QuantityBasis = (typeof QuantityBasisValues)[number];

export const SignoffModeValues = ["ONE_TIME_CODE", "SIGNED_DOCUMENT"] as const;
export type SignoffMode = (typeof SignoffModeValues)[number];

export const SignerKindValues = ["LISTED", "OUTSIDE"] as const;
export type SignerKind = (typeof SignerKindValues)[number];

export const SignoffStateValues = ["SIGNED", "VOID"] as const;
export type SignoffState = (typeof SignoffStateValues)[number];

export const EngagementOriginValues = ["CONNECTION", "OUTSIDE", "RFQ_SELECTION"] as const;
export type EngagementOrigin = (typeof EngagementOriginValues)[number];

export const PackageServiceKindValues = ["CONNECTION_ACCEPTED", "RFQ_SELECTION"] as const;
export type PackageServiceKind = (typeof PackageServiceKindValues)[number];

export const RfqStateValues = ["DRAFT", "ISSUED", "CLOSED", "CANCELLED"] as const;
export type RfqState = (typeof RfqStateValues)[number];

export const RfqCancelReasonValues = ["OWNER", "OPERATIONS", "PACKAGE_ENDED", "BASELINE_SUPERSEDED", "PROJECT_CLOSED"] as const;
export type RfqCancelReason = (typeof RfqCancelReasonValues)[number];

export const InvitationStateValues = ["PROPOSED", "SENT", "ACCEPTED", "DECLINED", "EXPIRED", "WITHDRAWN"] as const;
export type InvitationState = (typeof InvitationStateValues)[number];

export const InvitationSourceValues = ["NOMINATED", "INTRODUCED", "ENGAGED"] as const;
export type InvitationSource = (typeof InvitationSourceValues)[number];

export const InvitationWithdrawReasonValues = ["REMOVED", "OPERATIONS", "RFQ_CANCELLED", "RFQ_CLOSED", "NOT_LISTED"] as const;
export type InvitationWithdrawReason = (typeof InvitationWithdrawReasonValues)[number];

export const QuoteVersionStateValues = ["SUBMITTED", "SUPERSEDED", "WITHDRAWN", "EXPIRED", "SELECTED", "NOT_SELECTED"] as const;
export type QuoteVersionState = (typeof QuoteVersionStateValues)[number];

export const QuoteVersionKindValues = ["STANDARD", "RENEWAL"] as const;
export type QuoteVersionKind = (typeof QuoteVersionKindValues)[number];

export const QuoteCheckStateValues = ["PENDING", "NEEDS_CLARIFICATION", "REVIEWED", "CLOSED"] as const;
export type QuoteCheckState = (typeof QuoteCheckStateValues)[number];

export const TaxTreatmentValues = ["INCLUSIVE", "EXCLUSIVE"] as const;
export type TaxTreatment = (typeof TaxTreatmentValues)[number];

export const QuoteLineKindValues = ["RFQ_LINE", "ADDITIONAL"] as const;
export type QuoteLineKind = (typeof QuoteLineKindValues)[number];

export const DeviationTypeValues = ["EXCLUDED", "GRADE", "QUANTITY", "ADDITIONAL", "OTHER"] as const;
export type DeviationType = (typeof DeviationTypeValues)[number];

export const AdjustmentClarificationValues = ["NONE", "OPEN", "RESOLVED"] as const;
export type AdjustmentClarification = (typeof AdjustmentClarificationValues)[number];

export const ClarificationDirectionValues = ["CONTRACTOR_ASKS", "PLAN2BUILD_ASKS"] as const;
export type ClarificationDirection = (typeof ClarificationDirectionValues)[number];

export const ClarificationStateValues = ["OPEN", "ANSWERED", "CLOSED"] as const;
export type ClarificationState = (typeof ClarificationStateValues)[number];

export const ComparisonStateValues = ["PUBLISHED", "SUPERSEDED", "DECIDED"] as const;
export type ComparisonState = (typeof ComparisonStateValues)[number];

export const StageUpdateKindValues = ["PROGRESS", "COMPLETION_REQUEST"] as const;
export type StageUpdateKind = (typeof StageUpdateKindValues)[number];

export const PaymentMarkSideValues = ["PAID", "RECEIVED"] as const;
export type PaymentMarkSide = (typeof PaymentMarkSideValues)[number];

export const PaymentMarkValueValues = ["YES", "NO"] as const;
export type PaymentMarkValue = (typeof PaymentMarkValueValues)[number];

export const AppointmentStatusValues = ["ACTIVE", "ENDED"] as const;
export type AppointmentStatus = (typeof AppointmentStatusValues)[number];

export const ChecklistStatusValues = ["DRAFT", "PUBLISHED", "RETIRED"] as const;
export type ChecklistStatus = (typeof ChecklistStatusValues)[number];

export const InspectionKindValues = ["INITIAL", "REINSPECTION"] as const;
export type InspectionKind = (typeof InspectionKindValues)[number];

export const InspectionStateValues = ["SCHEDULED", "IN_PROGRESS", "SUBMITTED", "APPROVED", "RETURNED", "CANCELLED"] as const;
export type InspectionState = (typeof InspectionStateValues)[number];

export const InspectionCancelReasonValues = ["OPERATIONS", "PACKAGE_ENDED", "PROJECT_CLOSED"] as const;
export type InspectionCancelReason = (typeof InspectionCancelReasonValues)[number];

export const CheckpointResultValues = ["PASS", "OBSERVATION", "NON_CONFORMANCE", "NOT_APPLICABLE"] as const;
export type CheckpointResult = (typeof CheckpointResultValues)[number];

export const SeverityValues = ["MINOR", "MAJOR", "CRITICAL"] as const;
export type Severity = (typeof SeverityValues)[number];

export const NcStateValues = ["OPEN", "RECTIFICATION_SUBMITTED", "REINSPECTION_SCHEDULED", "CLOSED"] as const;
export type NcState = (typeof NcStateValues)[number];

export const HandoverStateValues = ["OPEN", "READY", "ACKNOWLEDGED", "ISSUED_BY_OPERATIONS"] as const;
export type HandoverState = (typeof HandoverStateValues)[number];

export const HandoverDocumentKindValues = ["WARRANTY", "MANUAL", "DRAWING", "CERTIFICATE", "PHOTO", "OTHER"] as const;
export type HandoverDocumentKind = (typeof HandoverDocumentKindValues)[number];

export const BuildRecordStateValues = ["DRAFT", "ISSUED", "SUPERSEDED"] as const;
export type BuildRecordState = (typeof BuildRecordStateValues)[number];

export const BuildRecordBasisValues = ["ACKNOWLEDGED", "ISSUED_BY_OPERATIONS"] as const;
export type BuildRecordBasis = (typeof BuildRecordBasisValues)[number];

export const FacingValues = ["N", "NE", "E", "SE", "S", "SW", "W", "NW"] as const;
export type Facing = (typeof FacingValues)[number];

export const SetbackSideValues = ["FRONT", "BACK", "LEFT", "RIGHT"] as const;
export type SetbackSide = (typeof SetbackSideValues)[number];

export const PlotEdgeKindValues = ["ROAD", "NEIGHBOUR"] as const;
export type PlotEdgeKind = (typeof PlotEdgeKindValues)[number];

export const SetbackSourceValues = ["REQUIREMENT", "DESIGN_INPUT"] as const;
export type SetbackSource = (typeof SetbackSourceValues)[number];

export const ParkingKindValues = ["CAR", "TWO_WHEELER"] as const;
export type ParkingKind = (typeof ParkingKindValues)[number];

export const ParkingPlacementValues = ["INSIDE_FOOTPRINT"] as const;
export type ParkingPlacement = (typeof ParkingPlacementValues)[number];

export const OriginKindValues = ["REQUIREMENT", "DESIGN_INPUT", "RULESET", "SOLVER", "USER_EDIT"] as const;
export type OriginKind = (typeof OriginKindValues)[number];

export const RoomTypeValues = ["LIVING", "DINING", "KITCHEN", "BEDROOM", "BATH_ATTACHED", "BATH_COMMON", "WC", "PUJA", "UTILITY", "STORE", "PASSAGE", "FOYER", "STAIR_HALL", "PARKING"] as const;
export type RoomType = (typeof RoomTypeValues)[number];

export const ZoneValues = ["PUBLIC", "PRIVATE", "SERVICE", "CIRCULATION", "OUTDOOR"] as const;
export type Zone = (typeof ZoneValues)[number];

export const WallKindValues = ["EXTERIOR", "INTERIOR"] as const;
export type WallKind = (typeof WallKindValues)[number];

export const OpeningKindValues = ["MAIN_ENTRANCE", "DOOR", "VOID", "WINDOW"] as const;
export type OpeningKind = (typeof OpeningKindValues)[number];

export const DoorLeafValues = ["SINGLE", "DOUBLE", "SLIDING"] as const;
export type DoorLeaf = (typeof DoorLeafValues)[number];

export const HingeSideValues = ["A_SIDE", "B_SIDE"] as const;
export type HingeSide = (typeof HingeSideValues)[number];

export const WallSideValues = ["LEFT", "RIGHT"] as const;
export type WallSide = (typeof WallSideValues)[number];

export const FixtureTypeValues = ["WC_WESTERN", "WC_INDIAN", "WASH_BASIN", "SHOWER_AREA", "KITCHEN_COUNTER", "KITCHEN_SINK"] as const;
export type FixtureType = (typeof FixtureTypeValues)[number];

export const ConstraintKindValues = ["ROOM_PRESENT", "ROOM_MIN_SIZE", "RELATION", "INSIDE_ENVELOPE", "ENTRANCE_ON_EDGE", "PARKING_PROVIDED", "AREA_DEVIATION", "DIMENSION_DEVIATION", "ASPECT_EXCESS", "CIRCULATION_SHARE", "OVERSIZE", "ADJACENCY", "WET_CLUSTER", "EXTERIOR_EXPOSURE", "PRIVACY", "PARKING_CONVENIENCE", "ZONE_ORDER", "ROOM_SIZE_OUTLIER", "BEDROOM_GROUPING", "ORIENTATION"] as const;
export type ConstraintKind = (typeof ConstraintKindValues)[number];

export const ConstraintStrengthValues = ["HARD", "SOFT"] as const;
export type ConstraintStrength = (typeof ConstraintStrengthValues)[number];

export const ConstraintOutcomeValues = ["MET", "PARTIAL", "RELAXED", "UNMET", "NOT_EVALUATED"] as const;
export type ConstraintOutcome = (typeof ConstraintOutcomeValues)[number];

export const RelationKindValues = ["ADJACENT_WITH_DOOR", "ADJACENT_OPEN"] as const;
export type RelationKind = (typeof RelationKindValues)[number];

export const OrientationModeValues = ["OFF", "SOFT", "SOFT_HIGH"] as const;
export type OrientationMode = (typeof OrientationModeValues)[number];

export const DiningArrangementValues = ["SEPARATE", "IN_LIVING"] as const;
export type DiningArrangement = (typeof DiningArrangementValues)[number];

export const KitchenArrangementValues = ["CLOSED", "OPEN"] as const;
export type KitchenArrangement = (typeof KitchenArrangementValues)[number];

export const StairChoiceValues = ["NONE", "INTERNAL", "EXTERNAL"] as const;
export type StairChoice = (typeof StairChoiceValues)[number];

export const DesignInputKeyValues = ["FACING", "SETBACK_FRONT", "SETBACK_BACK", "SETBACK_LEFT", "SETBACK_RIGHT", "BEDROOMS_EXACT", "BATHROOMS_EXACT", "ATTACHED_BATHROOMS", "PARKING_SPACES", "PARKING_KIND", "DINING", "KITCHEN", "STAIR", "UTILITY"] as const;
export type DesignInputKey = (typeof DesignInputKeyValues)[number];

export const MissingInputReasonValues = ["NOT_ANSWERED", "NOT_SURE", "OUT_OF_RANGE"] as const;
export type MissingInputReason = (typeof MissingInputReasonValues)[number];

export const UnsupportedReasonValues = ["QUESTION_SET_NOT_SUPPORTED", "ANSWER_INVALID", "PLOT_NOT_RECTANGULAR", "FLOORS_NOT_SUPPORTED", "BASEMENT_NOT_SUPPORTED", "STAIR_NOT_YET_SUPPORTED"] as const;
export type UnsupportedReason = (typeof UnsupportedReasonValues)[number];

export const InfeasibleReasonValues = ["ENVELOPE_EMPTY", "AREA_BUDGET", "WIDTH_TOO_NARROW", "DEPTH_EXCEEDED", "PARKING_TOO_WIDE", "ACCESS_SPAN", "FIXTURE_FIT", "OPENING_FIT", "RULESET_INCOMPLETE"] as const;
export type InfeasibleReason = (typeof InfeasibleReasonValues)[number];

export const PlanSourceValues = ["GENERATED", "EDITED", "REGENERATED"] as const;
export type PlanSource = (typeof PlanSourceValues)[number];

export const SolverKindValues = ["DETERMINISTIC_MVP", "ZONED_LOCAL_SEARCH", "CP_SAT"] as const;
export type SolverKind = (typeof SolverKindValues)[number];

export const RulesetStatusValues = ["DRAFT", "APPROVED", "PUBLISHED", "RETIRED"] as const;
export type RulesetStatus = (typeof RulesetStatusValues)[number];

export const PlanGenerationStateValues = ["QUEUED", "RUNNING", "VALID", "INFEASIBLE", "FAILED"] as const;
export type PlanGenerationState = (typeof PlanGenerationStateValues)[number];

export const PlanFailureReasonValues = ["ENGINE_ERROR", "ENGINE_INVALID_OUTPUT", "ENGINE_TIMEOUT", "STALE"] as const;
export type PlanFailureReason = (typeof PlanFailureReasonValues)[number];

export const PlanValidityValues = ["VALID", "INVALID"] as const;
export type PlanValidity = (typeof PlanValidityValues)[number];

export const ValidationCategoryValues = ["SCHEMA", "REFERENCES", "GEOMETRY", "OPENINGS", "FIXTURES", "CIRCULATION", "DIMENSIONS", "REQUIREMENTS"] as const;
export type ValidationCategory = (typeof ValidationCategoryValues)[number];

export const ValidationSeverityValues = ["ERROR", "WARNING"] as const;
export type ValidationSeverity = (typeof ValidationSeverityValues)[number];

export const RepairHintValues = ["AUTO", "USER", "NONE"] as const;
export type RepairHint = (typeof RepairHintValues)[number];

export const EntityKindValues = ["DOCUMENT", "PLOT", "ENVELOPE", "NODE", "WALL", "ROOM", "OPENING", "FIXTURE"] as const;
export type EntityKind = (typeof EntityKindValues)[number];

export const ValidationCodeValues = ["SCHEMA_INVALID", "SCHEMA_VERSION_UNSUPPORTED", "ID_DUPLICATE", "REF_MISSING", "PLOT_INVALID", "GEOMETRY_UNSUPPORTED_V1", "ROOM_POLYGON_INVALID", "ROOM_OVERLAP", "ROOM_OUTSIDE_ENVELOPE", "BUILDING_OUTSIDE_PLOT", "ROOM_EDGE_NOT_ON_WALL", "WALL_ZERO_LENGTH", "WALL_NOT_ORTHOGONAL", "WALL_OVERLAP", "WALL_DANGLING_END", "WALL_THICKNESS_INVALID", "OPENING_HOST_MISSING", "OPENING_OUTSIDE_HOST", "OPENING_OVERLAP", "OPENING_DIMENSION_INVALID", "WINDOW_ON_INTERIOR_WALL", "FIXTURE_HOST_MISSING", "FIXTURE_NOT_ON_ROOM_WALL", "FIXTURE_OUTSIDE_ROOM", "FIXTURE_NOT_PERMITTED_IN_ROOM", "FIXTURE_COUNT_EXCEEDS_SPEC", "FIXTURE_OVERLAP", "FIXTURE_CLEARANCE_BLOCKED", "FIXTURE_BLOCKS_OPENING", "ENTRANCE_MISSING", "ROOM_UNREACHABLE", "ROOM_BELOW_MIN_SHORT_SIDE", "ROOM_BELOW_MIN_AREA", "PASSAGE_TOO_NARROW", "HABITABLE_ROOM_NO_WINDOW", "ROOM_COUNT_MISMATCH", "PARKING_MISSING", "PARKING_TOO_SMALL", "RELATION_UNMET"] as const;
export type ValidationCode = (typeof ValidationCodeValues)[number];

export const PlanOpKindValues = ["MOVE_OPENING", "SET_OPENING", "ADD_OPENING", "DELETE_OPENING", "MOVE_FIXTURE", "ADD_FIXTURE", "DELETE_FIXTURE", "RENAME_ROOM", "SET_ROOM_TYPE", "MOVE_WALL", "ADD_ROOM", "DELETE_ROOM", "MOVE_EDGE", "REVERT_TO_REVISION", "REVERT_TO_VERSION"] as const;
export type PlanOpKind = (typeof PlanOpKindValues)[number];

export const TopologyFamilyValues = ["SPINE", "FRONT_EXTENSION", "SIDE_WING", "FRONT_LIVING_REAR_BEDROOM", "FRONT_PUBLIC_REAR_PRIVATE", "L_CIRCULATION", "CENTRAL_LIVING_BEDROOM_WINGS", "LINEAR_REAR_CORRIDOR"] as const;
export type TopologyFamily = (typeof TopologyFamilyValues)[number];

export const FeasibilityClassValues = ["PROVEN", "NO_SUPPORTED_LAYOUT"] as const;
export type FeasibilityClass = (typeof FeasibilityClassValues)[number];

export const RepairReasonValues = ["VALIDATION_ERROR", "OBJECTIVE"] as const;
export type RepairReason = (typeof RepairReasonValues)[number];

export const PlanOpRejectionValues = ["UNKNOWN_ENTITY", "ENTITY_EXISTS", "NOT_SUPPORTED", "NO_MOVEMENT", "NOT_AXIS_ALIGNED", "WALL_WOULD_COLLAPSE", "HOSTED_ITEM_LEAVES_WALL", "NOT_RECTANGULAR", "HOSTED_ITEM_CHANGES_ROOMS", "DOOR_DOES_NOT_FIT", "ROOMS_WOULD_OVERLAP", "NOT_A_SLICE", "ROOMS_NOT_MERGEABLE", "ROOM_TYPE_NOT_ALLOWED", "REVERT_NOT_ALONE", "UNKNOWN_REVISION", "LAST_KITCHEN_REQUIRED", "LAST_BATHROOM_REQUIRED"] as const;
export type PlanOpRejection = (typeof PlanOpRejectionValues)[number];

export const PlanOpReasonValues = ["USER", "AUTO_REPAIR", "REVERT"] as const;
export type PlanOpReason = (typeof PlanOpReasonValues)[number];

export const RoomSideValues = ["LEFT", "RIGHT", "FRONT", "BACK"] as const;
export type RoomSide = (typeof RoomSideValues)[number];

export const ProgrammeChangeValues = ["ROOM_ADDED_BY_OWNER", "ROOM_REMOVED_BY_OWNER", "ROOM_TYPE_CHANGED_BY_OWNER"] as const;
export type ProgrammeChange = (typeof ProgrammeChangeValues)[number];
