// Checkpoint 3: the concept floor plan page on the live stack, on a phone and a desktop. A real
// plan is generated by the engine (synthetic test ruleset, local only), drawn from the API's
// geometry, and edited through typed operations that the server validates. Runs only when the
// local stack has the houseplans feature on (see AI_DESIGN_ENGINE_CHECKPOINT_3_REPORT, section
// "How to run"); otherwise it is skipped.
import { readFileSync } from "node:fs";
import path from "node:path";

import { expect, test, type Page } from "@playwright/test";

import { ANSWERS, IHB, codeFor, expectAccessible, sql, uniqueEmail } from "./support";

// a 30 x 50 ft single-storey 2BHK with a two-wheeler (benchmark case 2bhk_30x50_north_twowheeler_open)
const PLAN_ANSWERS = {
  ...ANSWERS,
  plot_is_rectangular: true,
  floors: "G",
  basement: false,
  built_up_area_sqft: "NOT_SURE",
  plot_width_ft: 30,
  plot_depth_ft: 50,
  facing: "N",
  setbacks: { FRONT: 5, BACK: 3, LEFT: 2, RIGHT: 2 },
  bedrooms: "2",
  bathrooms: "1",
  pooja_room: false,
  car_parking: true,
  vastu: "NOT_NEEDED",
};
const DESIGN_INPUTS = {
  stair: "NONE",
  attached_bathrooms: 0,
  dining: "IN_LIVING",
  kitchen: "OPEN",
  utility: true,
  parking_spaces: 1,
  parking_kind: "TWO_WHEELER",
};

/** The synthetic test ruleset, installed once in the local database (local env only). */
function ensureRuleset(): void {
  const file = path.resolve(process.cwd(), "../api/tests/fixtures/houseplans/ruleset_synthetic_test_only.json");
  const content = readFileSync(file, "utf-8");
  sql(
    "INSERT INTO layout_rulesets (id, version, status, is_synthetic, schema_version, content, content_sha256, note) " +
      "SELECT gen_random_uuid(), 9001, 'DRAFT', true, '1.0.0', $json$" +
      content +
      "$json$::jsonb, repeat('0', 64), 'e2e synthetic test ruleset' " +
      "WHERE NOT EXISTS (SELECT 1 FROM layout_rulesets WHERE is_synthetic AND status = 'DRAFT');",
  );
}

type Call = (path: string, method: string, body?: unknown, key?: string) => Promise<{ status: number; body: any }>; // eslint-disable-line @typescript-eslint/no-explicit-any

function caller(page: Page): Call {
  return (p, method, body, key) =>
    page.evaluate(
      async ({ p, method, body, key }) => {
        const headers: Record<string, string> = {
          "Content-Type": "application/json",
          "X-Requested-With": "plan2build",
        };
        if (key) headers["Idempotency-Key"] = key;
        const response = await fetch(p, { method, headers, body: body === undefined ? undefined : JSON.stringify(body) });
        return { status: response.status, body: await response.json().catch(() => null) };
      },
      { p, method, body, key },
    );
}

/** A homeowner with a submitted requirement and a VALID floor plan; null when the feature is off. */
async function plannedProject(page: Page, request: Parameters<typeof codeFor>[0]) {
  const email = uniqueEmail();
  await page.goto(`${IHB}/sign-in`);
  const call = caller(page);
  const started = await call("/api/v1/auth/otp/start", "POST", { email });
  const code = await codeFor(request, email);
  await call("/api/v1/auth/otp/verify", "POST", { challenge_id: started.body.challenge_id, code });
  const created = await call("/api/v1/projects", "POST", { city: "Raipur" }, crypto.randomUUID());
  const id = created.body.project.project_id as string;
  await call(`/api/v1/projects/${id}/requirement`, "PUT", { answers: PLAN_ANSWERS, version: 1 });
  const submitted = await call(`/api/v1/projects/${id}/requirement/submit`, "POST", { version: 2 }, crypto.randomUUID());
  expect(submitted.status).toBe(200);
  const listed = await call(`/api/v1/projects/${id}/house-plans`, "GET");
  if (listed.status === 404) return null;
  ensureRuleset();
  const requested = await call(
    `/api/v1/projects/${id}/house-plans`,
    "POST",
    { design_inputs: DESIGN_INPUTS },
    crypto.randomUUID(),
  );
  expect(requested.status, JSON.stringify(requested.body)).toBe(202);
  const planId = requested.body.plan_id as string;
  let detail: { status: number; body: any } = { status: 0, body: null }; // eslint-disable-line @typescript-eslint/no-explicit-any
  await expect(async () => {
    detail = await call(`/api/v1/projects/${id}/house-plans/${planId}`, "GET");
    expect(detail.body.state).toBe("VALID");
  }).toPass({ timeout: 60_000 });
  return { id, planId, call, detail: detail.body };
}

test("a generated floor plan is drawn from its geometry and edited through validated operations", async ({
  page,
  request,
}) => {
  const planned = await plannedProject(page, request);
  test.skip(planned === null, "the houseplans feature is off on this stack");
  if (!planned) return;
  const { id, planId, call, detail } = planned;
  const floor = detail.geometry.floors[0];

  // the designs page lists it
  await page.goto(`${IHB}/projects/${id}/designs`);
  await expect(page.getByRole("heading", { name: "Your floor plans" })).toBeVisible();
  await page.getByRole("link", { name: "Open floor plan" }).click();
  await page.waitForURL(`**/projects/${id}/designs/plans/${planId}`);

  // the drawing, the persistent disclaimer and the text alternative
  await expect(page.getByText("Concept floor plan. Not a construction, structural or approval drawing.")).toBeVisible();
  await expect(page.getByText("Rules not yet verified")).toBeVisible();
  const drawing = page.locator("svg[data-plan-drawing]");
  await expect(drawing).toBeVisible();
  await expect(drawing.locator("[data-room]")).toHaveCount(floor.rooms.length);
  await expect(drawing.locator("[data-opening-id]")).toHaveCount(floor.openings.length);
  for (const room of floor.rooms) {
    await expect(page.getByRole("button", { name: new RegExp(`^${room.name}`) })).toBeVisible();
  }
  await expect(page.getByText("All checks passed.")).toBeVisible();
  await expectAccessible(page);

  const phone = (page.viewportSize()?.width ?? 0) < 768;
  if (phone) {
    // phones view; editing is for tablets and computers (AD-14)
    await expect(page.getByText("Open this plan on a tablet or computer to change it.")).toBeVisible();
    await expect(page.getByRole("button", { name: "Undo" })).toHaveCount(0);
    return;
  }

  // an edit: select the living room, nudge it with the keyboard; the server decides
  const canvas = page.locator("[data-plan-canvas]");
  const idle = page.locator("[data-plan-canvas]:not([data-busy])");
  const living = floor.rooms.find((r: { type: string }) => r.type === "LIVING");
  await page.getByRole("button", { name: new RegExp(`^${living.name}`) }).click();
  await canvas.focus();
  await page.keyboard.press("ArrowUp");
  const saved = page.getByText("Change saved.");
  const refused = page.getByText("That change was not saved");
  await expect(saved.or(refused)).toBeVisible({ timeout: 15_000 });
  let revision = (await call(`/api/v1/projects/${id}/house-plans/${planId}`, "GET")).body.editing.revision_no;
  if (await refused.isVisible()) {
    // refused: nothing was stored, the plan is exactly as generated
    const after = await call(`/api/v1/projects/${id}/house-plans/${planId}`, "GET");
    expect(after.body.editing.revision_no).toBe(0);
    expect(after.body.document).toEqual(detail.document);
    await expectAccessible(page);
  }

  // keyboard only: pick a room, pick one of its sides, nudge it, until the server accepts one
  const arrows: Record<string, string[]> = {
    "Left side": ["ArrowLeft", "ArrowRight"],
    "Right side": ["ArrowRight", "ArrowLeft"],
    "Front side": ["ArrowDown", "ArrowUp"],
    "Back side": ["ArrowUp", "ArrowDown"],
  };
  const sides = page.getByRole("group", { name: "Choose a side to move" });
  search: for (const room of floor.rooms) {
    if (revision > 0) break;
    await page.getByRole("button", { name: new RegExp(`^${room.name}`) }).click();
    for (const label of Object.keys(arrows)) {
      const button = sides.getByRole("button", { name: label });
      if ((await button.count()) === 0) continue;
      for (const key of arrows[label]) {
        await button.click();
        await page.keyboard.press(key);
        await expect(idle).toBeVisible({ timeout: 15_000 });
        revision = (await call(`/api/v1/projects/${id}/house-plans/${planId}`, "GET")).body.editing.revision_no;
        if (revision > 0) break search;
      }
    }
  }
  expect(revision, "no side move was accepted").toBe(1);
  const after = await call(`/api/v1/projects/${id}/house-plans/${planId}`, "GET");
  expect(after.body.document.meta.source).toBe("EDITED");
  expect(after.body.validation.valid).toBe(true);
  await expect(saved).toBeVisible();

  // undo sends the inverse batch; the plan returns to the generated body
  await page.getByRole("button", { name: "Undo" }).click();
  await expect(async () => {
    const undone = await call(`/api/v1/projects/${id}/house-plans/${planId}`, "GET");
    expect(undone.body.editing.revision_no).toBe(2);
    expect(undone.body.document.meta.body_sha256).toBe(detail.document.meta.body_sha256);
  }).toPass({ timeout: 15_000 });
  await expect(page.getByRole("button", { name: "Redo" })).toBeEnabled();
  await expectAccessible(page);
});
