"""Slice 3.6: RFQ to contractor selection (SLICE3_6_READINESS section 0; ADR-024).

Revision ID: 0015
Revises: 0014
Create Date: 2026-10-06

The rfq module's tables, guarded like 3.3 to 3.5 (lifecycle columns only, append-only history,
set-once records), and adjustments editable only while their quote's review is open. The
engagements module records how an engagement started (origin; RFQ_SELECTION with the contacts
exchanged at selection, ADR-024). Billing's substantial-work kinds become a closed set:
CONNECTION_ACCEPTED (N-12) and RFQ_SELECTION (QD-02, a new product decision). New file purposes
and the SELECT_QUOTE confirmation purpose. The selection statement version 1 is functional
wording: IMPLEMENTED / PENDING FINAL CLIENT + LEGAL CONFIRMATION (QD-12).
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0015"
down_revision: str | None = "0014"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "selection_statements",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=10), nullable=False),
        sa.Column("note", sa.Text(), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("activated_by", sa.Uuid(), nullable=True),
        sa.Column("activated_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status IN ('DRAFT', 'ACTIVE', 'RETIRED')", name=op.f("ck_selection_statements_status")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_selection_statements")),
        sa.UniqueConstraint("version", name=op.f("uq_selection_statements_version")),
    )
    op.create_index(
        "uq_selection_statements_one_active",
        "selection_statements",
        ["status"],
        unique=True,
        postgresql_where=sa.text("status = 'ACTIVE'"),
    )
    op.create_table(
        "rfqs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("category_code", sa.String(length=40), nullable=False),
        sa.Column("build_plan_version_id", sa.Uuid(), nullable=False),
        sa.Column("state", sa.String(length=10), nullable=False),
        sa.Column("max_recipients", sa.Integer(), nullable=False),
        sa.Column("quotes_due_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("manifest", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("manifest_sha256", sa.String(length=64), nullable=True),
        sa.Column("requested_by", sa.Uuid(), nullable=False),
        sa.Column("requested_role", sa.String(length=12), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("issued_by", sa.Uuid(), nullable=True),
        sa.Column("issued_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deadline_noticed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancel_reason", sa.String(length=20), nullable=True),
        sa.Column("cancel_note", sa.Text(), nullable=True),
        sa.Column("cancelled_by_role", sa.String(length=12), nullable=True),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.CheckConstraint(
            "(state = 'CANCELLED') = (cancel_reason IS NOT NULL)",
            name=op.f("ck_rfqs_cancelled_has_reason"),
        ),
        sa.CheckConstraint(
            "cancel_reason IS NULL OR cancel_reason IN ('OWNER', 'OPERATIONS', 'PACKAGE_ENDED', 'BASELINE_SUPERSEDED', 'PROJECT_CLOSED')",
            name=op.f("ck_rfqs_cancel_reason"),
        ),
        sa.CheckConstraint("category_code = 'CONTRACTOR'", name=op.f("ck_rfqs_contractor_only")),
        sa.CheckConstraint(
            "state IN ('DRAFT', 'ISSUED', 'CLOSED', 'CANCELLED')", name=op.f("ck_rfqs_state")
        ),
        sa.CheckConstraint(
            "state NOT IN ('ISSUED', 'CLOSED') OR (manifest IS NOT NULL AND manifest_sha256 IS NOT NULL AND issued_at IS NOT NULL AND quotes_due_at IS NOT NULL)",
            name=op.f("ck_rfqs_issued_is_frozen"),
        ),
        sa.CheckConstraint("max_recipients > 0", name=op.f("ck_rfqs_max_recipients")),
        sa.ForeignKeyConstraint(
            ["build_plan_version_id"],
            ["build_plan_versions.id"],
            name=op.f("fk_rfqs_build_plan_version_id_build_plan_versions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["category_code"],
            ["service_categories.code"],
            name=op.f("fk_rfqs_category_code_service_categories"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["issued_by"], ["users.id"], name=op.f("fk_rfqs_issued_by_users"), ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_rfqs_project_id_projects"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["requested_by"],
            ["users.id"],
            name=op.f("fk_rfqs_requested_by_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_rfqs")),
    )
    op.create_index("ix_rfqs_project_id", "rfqs", ["project_id", "created_at"], unique=False)
    op.create_index(
        "uq_rfqs_one_open",
        "rfqs",
        ["project_id", "category_code"],
        unique=True,
        postgresql_where=sa.text("state IN ('DRAFT', 'ISSUED')"),
    )
    op.create_table(
        "comparisons",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("rfq_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("version_no", sa.Integer(), nullable=False),
        sa.Column("state", sa.String(length=10), nullable=False),
        sa.Column("quote_version_ids", postgresql.ARRAY(sa.Uuid()), nullable=False),
        sa.Column("order_seed", sa.String(length=64), nullable=False),
        sa.Column("snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("snapshot_sha256", sa.String(length=64), nullable=False),
        sa.Column("document_file_id", sa.Uuid(), nullable=False),
        sa.Column("published_by", sa.Uuid(), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.CheckConstraint(
            "state IN ('PUBLISHED', 'SUPERSEDED', 'DECIDED')", name=op.f("ck_comparisons_state")
        ),
        sa.CheckConstraint(
            "cardinality(quote_version_ids) >= 1", name=op.f("ck_comparisons_not_empty")
        ),
        sa.ForeignKeyConstraint(
            ["document_file_id"],
            ["file_objects.id"],
            name=op.f("fk_comparisons_document_file_id_file_objects"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_comparisons_project_id_projects"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["published_by"],
            ["users.id"],
            name=op.f("fk_comparisons_published_by_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["rfq_id"], ["rfqs.id"], name=op.f("fk_comparisons_rfq_id_rfqs"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_comparisons")),
        sa.UniqueConstraint("rfq_id", "version_no", name=op.f("uq_comparisons_rfq_id_version_no")),
    )
    op.create_index(
        "uq_comparisons_one_current",
        "comparisons",
        ["rfq_id"],
        unique=True,
        postgresql_where=sa.text("state IN ('PUBLISHED', 'DECIDED')"),
    )
    op.create_table(
        "rfq_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("rfq_id", sa.Uuid(), nullable=False),
        sa.Column("subject", sa.String(length=14), nullable=False),
        sa.Column("subject_id", sa.Uuid(), nullable=False),
        sa.Column("from_state", sa.String(length=20), nullable=True),
        sa.Column("to_state", sa.String(length=20), nullable=False),
        sa.Column("actor_user_id", sa.Uuid(), nullable=True),
        sa.Column("actor_role", sa.String(length=12), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column(
            "at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.CheckConstraint(
            "subject IN ('RFQ', 'INVITATION', 'QUOTE_VERSION', 'REVIEW', 'CLARIFICATION', 'COMPARISON', 'SELECTION')",
            name=op.f("ck_rfq_events_subject"),
        ),
        sa.ForeignKeyConstraint(
            ["actor_user_id"],
            ["users.id"],
            name=op.f("fk_rfq_events_actor_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_rfq_events_project_id_projects"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["rfq_id"], ["rfqs.id"], name=op.f("fk_rfq_events_rfq_id_rfqs"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_rfq_events")),
    )
    op.create_index("ix_rfq_events_rfq_id", "rfq_events", ["rfq_id", "at"], unique=False)
    op.create_table(
        "rfq_invitations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("rfq_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("party", sa.String(length=8), nullable=False),
        sa.Column("profile_id", sa.Uuid(), nullable=True),
        sa.Column("engagement_id", sa.Uuid(), nullable=True),
        sa.Column("source", sa.String(length=12), nullable=False),
        sa.Column("introduced_reason", sa.Text(), nullable=True),
        sa.Column("state", sa.String(length=10), nullable=False),
        sa.Column("brief", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("respond_by", sa.DateTime(timezone=True), nullable=True),
        sa.Column("responded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("professional_contact", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("decline_reason", sa.String(length=24), nullable=True),
        sa.Column("decline_note", sa.Text(), nullable=True),
        sa.Column("withdraw_reason", sa.String(length=16), nullable=True),
        sa.Column("withdraw_note", sa.Text(), nullable=True),
        sa.Column("withdrawn_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.CheckConstraint(
            "(party = 'LISTED' AND profile_id IS NOT NULL AND engagement_id IS NULL) OR (party = 'OUTSIDE' AND profile_id IS NULL AND engagement_id IS NOT NULL AND source = 'ENGAGED')",
            name=op.f("ck_rfq_invitations_party_fields"),
        ),
        sa.CheckConstraint(
            "(state = 'DECLINED') = (decline_reason IS NOT NULL)",
            name=op.f("ck_rfq_invitations_declined_has_reason"),
        ),
        sa.CheckConstraint(
            "(state = 'WITHDRAWN') = (withdraw_reason IS NOT NULL)",
            name=op.f("ck_rfq_invitations_withdrawn_has_reason"),
        ),
        sa.CheckConstraint(
            "decline_reason IS DISTINCT FROM 'OTHER' OR length(trim(decline_note)) > 0",
            name=op.f("ck_rfq_invitations_other_needs_note"),
        ),
        sa.CheckConstraint(
            "decline_reason IS NULL OR decline_reason IN ('UNAVAILABLE', 'OUTSIDE_SERVICE_AREA', 'SCOPE_MISMATCH', 'SCHEDULE_MISMATCH', 'COMPLIANCE', 'ALREADY_ENGAGED', 'OTHER')",
            name=op.f("ck_rfq_invitations_decline_reason"),
        ),
        sa.CheckConstraint("party IN ('LISTED', 'OUTSIDE')", name=op.f("ck_rfq_invitations_party")),
        sa.CheckConstraint(
            "source <> 'INTRODUCED' OR length(trim(introduced_reason)) > 0",
            name=op.f("ck_rfq_invitations_introduced_has_reason"),
        ),
        sa.CheckConstraint(
            "source IN ('NOMINATED', 'INTRODUCED', 'ENGAGED')",
            name=op.f("ck_rfq_invitations_source"),
        ),
        sa.CheckConstraint(
            "state IN ('PROPOSED', 'SENT', 'ACCEPTED', 'DECLINED', 'EXPIRED', 'WITHDRAWN')",
            name=op.f("ck_rfq_invitations_state"),
        ),
        sa.CheckConstraint(
            "withdraw_reason IS NULL OR withdraw_reason IN ('REMOVED', 'OPERATIONS', 'RFQ_CANCELLED', 'RFQ_CLOSED', 'NOT_LISTED')",
            name=op.f("ck_rfq_invitations_withdraw_reason"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_rfq_invitations_created_by_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["engagement_id"],
            ["project_engagements.id"],
            name=op.f("fk_rfq_invitations_engagement_id_project_engagements"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["professional_profiles.id"],
            name=op.f("fk_rfq_invitations_profile_id_professional_profiles"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_rfq_invitations_project_id_projects"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["rfq_id"],
            ["rfqs.id"],
            name=op.f("fk_rfq_invitations_rfq_id_rfqs"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_rfq_invitations")),
    )
    op.create_index(
        "ix_rfq_invitations_open",
        "rfq_invitations",
        ["respond_by"],
        unique=False,
        postgresql_where=sa.text("state = 'SENT'"),
    )
    op.create_index(
        "ix_rfq_invitations_profile_id", "rfq_invitations", ["profile_id", "state"], unique=False
    )
    op.create_index(
        "uq_rfq_invitations_one_outside",
        "rfq_invitations",
        ["rfq_id"],
        unique=True,
        postgresql_where=sa.text("party = 'OUTSIDE'"),
    )
    op.create_index(
        "uq_rfq_invitations_one_per_contractor",
        "rfq_invitations",
        ["rfq_id", "profile_id"],
        unique=True,
        postgresql_where=sa.text("profile_id IS NOT NULL"),
    )
    op.create_table(
        "quote_drafts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("invitation_id", sa.Uuid(), nullable=False),
        sa.Column("content", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("updated_by", sa.Uuid(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.ForeignKeyConstraint(
            ["invitation_id"],
            ["rfq_invitations.id"],
            name=op.f("fk_quote_drafts_invitation_id_rfq_invitations"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["users.id"],
            name=op.f("fk_quote_drafts_updated_by_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_quote_drafts")),
        sa.UniqueConstraint("invitation_id", name=op.f("uq_quote_drafts_invitation_id")),
    )
    op.create_table(
        "quote_versions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("invitation_id", sa.Uuid(), nullable=False),
        sa.Column("rfq_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("version_no", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=8), nullable=False),
        sa.Column("renewal_of", sa.Uuid(), nullable=True),
        sa.Column("state", sa.String(length=12), nullable=False),
        sa.Column("review_state", sa.String(length=20), nullable=False),
        sa.Column("valid_from", sa.Date(), nullable=False),
        sa.Column("valid_to", sa.Date(), nullable=False),
        sa.Column("tax_treatment", sa.String(length=10), nullable=False),
        sa.Column("tax_note", sa.Text(), nullable=True),
        sa.Column("duration_days", sa.Integer(), nullable=False),
        sa.Column("stage_durations", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("payment_terms", sa.Text(), nullable=True),
        sa.Column("warranty", sa.Text(), nullable=True),
        sa.Column("materials", sa.Text(), nullable=True),
        sa.Column("exclusions", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("assumptions", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("attachment_file_ids", postgresql.ARRAY(sa.Uuid()), nullable=False),
        sa.Column("comparable_total", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("additional_total", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("content_sha256", sa.String(length=64), nullable=False),
        sa.Column("submitted_by", sa.Uuid(), nullable=False),
        sa.Column(
            "submitted_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("captured_by_staff", sa.Boolean(), nullable=False),
        sa.Column("evidence_file_id", sa.Uuid(), nullable=True),
        sa.Column("withdraw_reason", sa.Text(), nullable=True),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reviewed_by", sa.Uuid(), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.CheckConstraint(
            "(kind = 'RENEWAL') = (renewal_of IS NOT NULL)",
            name=op.f("ck_quote_versions_renewal_of"),
        ),
        sa.CheckConstraint(
            "(state = 'WITHDRAWN') = (withdraw_reason IS NOT NULL)",
            name=op.f("ck_quote_versions_withdrawn"),
        ),
        sa.CheckConstraint("kind IN ('STANDARD', 'RENEWAL')", name=op.f("ck_quote_versions_kind")),
        sa.CheckConstraint(
            "review_state IN ('PENDING', 'NEEDS_CLARIFICATION', 'REVIEWED', 'CLOSED')",
            name=op.f("ck_quote_versions_review_state"),
        ),
        sa.CheckConstraint(
            "state IN ('SUBMITTED', 'SUPERSEDED', 'WITHDRAWN', 'EXPIRED', 'SELECTED', 'NOT_SELECTED')",
            name=op.f("ck_quote_versions_state"),
        ),
        sa.CheckConstraint(
            "tax_treatment IN ('INCLUSIVE', 'EXCLUSIVE')",
            name=op.f("ck_quote_versions_tax_treatment"),
        ),
        sa.CheckConstraint(
            "NOT captured_by_staff OR evidence_file_id IS NOT NULL",
            name=op.f("ck_quote_versions_capture_has_evidence"),
        ),
        sa.CheckConstraint("duration_days > 0", name=op.f("ck_quote_versions_duration")),
        sa.CheckConstraint("valid_to > valid_from", name=op.f("ck_quote_versions_validity")),
        sa.ForeignKeyConstraint(
            ["evidence_file_id"],
            ["file_objects.id"],
            name=op.f("fk_quote_versions_evidence_file_id_file_objects"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["invitation_id"],
            ["rfq_invitations.id"],
            name=op.f("fk_quote_versions_invitation_id_rfq_invitations"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_quote_versions_project_id_projects"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["renewal_of"],
            ["quote_versions.id"],
            name=op.f("fk_quote_versions_renewal_of_quote_versions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["reviewed_by"],
            ["users.id"],
            name=op.f("fk_quote_versions_reviewed_by_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["rfq_id"], ["rfqs.id"], name=op.f("fk_quote_versions_rfq_id_rfqs"), ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["submitted_by"],
            ["users.id"],
            name=op.f("fk_quote_versions_submitted_by_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_quote_versions")),
        sa.UniqueConstraint(
            "invitation_id", "version_no", name=op.f("uq_quote_versions_invitation_id_version_no")
        ),
    )
    op.create_index(
        "ix_quote_versions_open",
        "quote_versions",
        ["valid_to"],
        unique=False,
        postgresql_where=sa.text("state = 'SUBMITTED'"),
    )
    op.create_index("ix_quote_versions_rfq_id", "quote_versions", ["rfq_id", "state"], unique=False)
    op.create_table(
        "quote_adjustments",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("quote_version_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("line_no", sa.Integer(), nullable=True),
        sa.Column("spec_line_code", sa.String(length=8), nullable=True),
        sa.Column("deviation_type", sa.String(length=10), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("rupee_impact", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("basis_note", sa.Text(), nullable=True),
        sa.Column("clarification_status", sa.String(length=10), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "clarification_status IN ('NONE', 'OPEN', 'RESOLVED')",
            name=op.f("ck_quote_adjustments_clarification_status"),
        ),
        sa.CheckConstraint(
            "deviation_type IN ('EXCLUDED', 'GRADE', 'QUANTITY', 'ADDITIONAL', 'OTHER')",
            name=op.f("ck_quote_adjustments_deviation_type"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_quote_adjustments_created_by_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_quote_adjustments_project_id_projects"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["quote_version_id"],
            ["quote_versions.id"],
            name=op.f("fk_quote_adjustments_quote_version_id_quote_versions"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_quote_adjustments")),
    )
    op.create_index(
        "ix_quote_adjustments_quote_version_id",
        "quote_adjustments",
        ["quote_version_id"],
        unique=False,
    )
    op.create_table(
        "quote_lines",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("quote_version_id", sa.Uuid(), nullable=False),
        sa.Column("kind", sa.String(length=10), nullable=False),
        sa.Column("line_no", sa.Integer(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("unit", sa.String(length=20), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=14, scale=3), nullable=False),
        sa.Column("rate", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("amount", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("is_excluded", sa.Boolean(), nullable=False),
        sa.Column("exclusion_reason", sa.Text(), nullable=True),
        sa.Column("alternate_spec", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "kind = 'RFQ_LINE' OR NOT is_excluded", name=op.f("ck_quote_lines_additional_priced")
        ),
        sa.CheckConstraint("kind IN ('RFQ_LINE', 'ADDITIONAL')", name=op.f("ck_quote_lines_kind")),
        sa.CheckConstraint(
            "(is_excluded AND rate IS NULL AND amount IS NULL AND length(trim(exclusion_reason)) > 0) OR (NOT is_excluded AND rate > 0 AND amount IS NOT NULL AND exclusion_reason IS NULL)",
            name=op.f("ck_quote_lines_priced_or_excluded"),
        ),
        sa.ForeignKeyConstraint(
            ["quote_version_id"],
            ["quote_versions.id"],
            name=op.f("fk_quote_lines_quote_version_id_quote_versions"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_quote_lines")),
        sa.UniqueConstraint(
            "quote_version_id",
            "kind",
            "line_no",
            name=op.f("uq_quote_lines_quote_version_id_kind_line_no"),
        ),
    )
    op.create_table(
        "rfq_clarifications",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("rfq_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("invitation_id", sa.Uuid(), nullable=False),
        sa.Column("quote_version_id", sa.Uuid(), nullable=True),
        sa.Column("direction", sa.String(length=16), nullable=False),
        sa.Column("question", sa.Text(), nullable=False),
        sa.Column("answer", sa.Text(), nullable=True),
        sa.Column("shared_with_all", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("state", sa.String(length=10), nullable=False),
        sa.Column("asked_by", sa.Uuid(), nullable=False),
        sa.Column(
            "asked_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("answered_by", sa.Uuid(), nullable=True),
        sa.Column("answered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("close_reason", sa.Text(), nullable=True),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.CheckConstraint(
            "(state = 'ANSWERED') = (answer IS NOT NULL)",
            name=op.f("ck_rfq_clarifications_answered"),
        ),
        sa.CheckConstraint(
            "NOT shared_with_all OR direction = 'CONTRACTOR_ASKS'",
            name=op.f("ck_rfq_clarifications_shared_questions"),
        ),
        sa.CheckConstraint(
            "direction IN ('CONTRACTOR_ASKS', 'PLAN2BUILD_ASKS')",
            name=op.f("ck_rfq_clarifications_direction"),
        ),
        sa.CheckConstraint(
            "state IN ('OPEN', 'ANSWERED', 'CLOSED')", name=op.f("ck_rfq_clarifications_state")
        ),
        sa.ForeignKeyConstraint(
            ["answered_by"],
            ["users.id"],
            name=op.f("fk_rfq_clarifications_answered_by_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["asked_by"],
            ["users.id"],
            name=op.f("fk_rfq_clarifications_asked_by_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["invitation_id"],
            ["rfq_invitations.id"],
            name=op.f("fk_rfq_clarifications_invitation_id_rfq_invitations"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_rfq_clarifications_project_id_projects"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["quote_version_id"],
            ["quote_versions.id"],
            name=op.f("fk_rfq_clarifications_quote_version_id_quote_versions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["rfq_id"],
            ["rfqs.id"],
            name=op.f("fk_rfq_clarifications_rfq_id_rfqs"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_rfq_clarifications")),
    )
    op.create_index(
        "ix_rfq_clarifications_rfq_id", "rfq_clarifications", ["rfq_id", "asked_at"], unique=False
    )
    op.create_table(
        "selections",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("rfq_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("comparison_id", sa.Uuid(), nullable=False),
        sa.Column("quote_version_id", sa.Uuid(), nullable=False),
        sa.Column("invitation_id", sa.Uuid(), nullable=False),
        sa.Column("engagement_id", sa.Uuid(), nullable=False),
        sa.Column("engagement_created", sa.Boolean(), nullable=False),
        sa.Column("selected_by", sa.Uuid(), nullable=False),
        sa.Column("challenge_id", sa.Uuid(), nullable=False),
        sa.Column("statement_id", sa.Uuid(), nullable=False),
        sa.Column("statement_text", sa.Text(), nullable=False),
        sa.Column("ip_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "selected_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["challenge_id"],
            ["otp_challenges.id"],
            name=op.f("fk_selections_challenge_id_otp_challenges"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["comparison_id"],
            ["comparisons.id"],
            name=op.f("fk_selections_comparison_id_comparisons"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["engagement_id"],
            ["project_engagements.id"],
            name=op.f("fk_selections_engagement_id_project_engagements"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["invitation_id"],
            ["rfq_invitations.id"],
            name=op.f("fk_selections_invitation_id_rfq_invitations"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_selections_project_id_projects"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["quote_version_id"],
            ["quote_versions.id"],
            name=op.f("fk_selections_quote_version_id_quote_versions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["rfq_id"], ["rfqs.id"], name=op.f("fk_selections_rfq_id_rfqs"), ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["selected_by"],
            ["users.id"],
            name=op.f("fk_selections_selected_by_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["statement_id"],
            ["selection_statements.id"],
            name=op.f("fk_selections_statement_id_selection_statements"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_selections")),
        sa.UniqueConstraint("challenge_id", name=op.f("uq_selections_challenge_id")),
        sa.UniqueConstraint("quote_version_id", name=op.f("uq_selections_quote_version_id")),
        sa.UniqueConstraint("rfq_id", name=op.f("uq_selections_rfq_id")),
    )
    op.add_column("project_engagements", sa.Column("origin", sa.String(length=14), nullable=True))
    op.add_column("project_engagements", sa.Column("selection_id", sa.Uuid(), nullable=True))
    op.add_column(
        "project_engagements",
        sa.Column("family_contact", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    op.add_column(
        "project_engagements",
        sa.Column("professional_contact", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    op.create_unique_constraint(
        op.f("uq_project_engagements_selection_id"), "project_engagements", ["selection_id"]
    )
    _upgrade_guards()


def downgrade() -> None:
    _downgrade_data()
    op.drop_constraint(
        op.f("uq_project_engagements_selection_id"), "project_engagements", type_="unique"
    )
    op.drop_column("project_engagements", "professional_contact")
    op.drop_column("project_engagements", "family_contact")
    op.drop_column("project_engagements", "selection_id")
    op.drop_column("project_engagements", "origin")
    op.drop_table("selections")
    op.drop_index("ix_rfq_clarifications_rfq_id", table_name="rfq_clarifications")
    op.drop_table("rfq_clarifications")
    op.drop_table("quote_lines")
    op.drop_index("ix_quote_adjustments_quote_version_id", table_name="quote_adjustments")
    op.drop_table("quote_adjustments")
    op.drop_index("ix_quote_versions_rfq_id", table_name="quote_versions")
    op.drop_index(
        "ix_quote_versions_open",
        table_name="quote_versions",
        postgresql_where=sa.text("state = 'SUBMITTED'"),
    )
    op.drop_table("quote_versions")
    op.drop_table("quote_drafts")
    op.drop_index(
        "uq_rfq_invitations_one_per_contractor",
        table_name="rfq_invitations",
        postgresql_where=sa.text("profile_id IS NOT NULL"),
    )
    op.drop_index(
        "uq_rfq_invitations_one_outside",
        table_name="rfq_invitations",
        postgresql_where=sa.text("party = 'OUTSIDE'"),
    )
    op.drop_index("ix_rfq_invitations_profile_id", table_name="rfq_invitations")
    op.drop_index(
        "ix_rfq_invitations_open",
        table_name="rfq_invitations",
        postgresql_where=sa.text("state = 'SENT'"),
    )
    op.drop_table("rfq_invitations")
    op.drop_index("ix_rfq_events_rfq_id", table_name="rfq_events")
    op.drop_table("rfq_events")
    op.drop_index(
        "uq_comparisons_one_current",
        table_name="comparisons",
        postgresql_where=sa.text("state IN ('PUBLISHED', 'DECIDED')"),
    )
    op.drop_table("comparisons")
    op.drop_index(
        "uq_rfqs_one_open",
        table_name="rfqs",
        postgresql_where=sa.text("state IN ('DRAFT', 'ISSUED')"),
    )
    op.drop_index("ix_rfqs_project_id", table_name="rfqs")
    op.drop_table("rfqs")
    op.drop_index(
        "uq_selection_statements_one_active",
        table_name="selection_statements",
        postgresql_where=sa.text("status = 'ACTIVE'"),
    )
    op.drop_table("selection_statements")
    _downgrade_tail()


PURPOSES_BEFORE = (
    "'REQUIREMENT_UPLOAD', 'AI_CONCEPT', 'VERIFICATION_EVIDENCE', 'PORTFOLIO', 'INVOICE', "
    "'QUOTE_DOCUMENT', 'DRAWING', 'BUILD_PLAN_EVIDENCE', 'BUILD_PLAN_DOCUMENT'"
)
STATEMENT_V1_ID = "36000000-0000-7000-8000-000000000001"
STATEMENT_V1 = (
    "I select quote version $version_no from $contractor for contractor work on project "
    "$project_code. I understand that Plan2Build is not the contractor, is not a party to the "
    "construction contract, receives no construction money and does not guarantee the quoted "
    "price. The construction contract and its payments are between me and the contractor."
)
MUTABLE_COLUMNS = {
    "rfqs": (
        "state", "quotes_due_at", "manifest", "manifest_sha256", "issued_by", "issued_at",
        "deadline_noticed_at", "closed_at", "cancel_reason", "cancel_note", "cancelled_by_role",
        "cancelled_at", "version",
    ),
    "rfq_invitations": (
        "state", "sent_at", "respond_by", "responded_at", "professional_contact",
        "decline_reason", "decline_note", "withdraw_reason", "withdraw_note", "withdrawn_at",
        "version",
    ),
    "quote_versions": (
        "state", "review_state", "withdraw_reason", "closed_at", "reviewed_by", "reviewed_at",
        "version",
    ),
    "rfq_clarifications": (
        "answer", "shared_with_all", "state", "answered_by", "answered_at", "close_reason",
        "version",
    ),
    "comparisons": ("state", "version"),
    "selection_statements": ("status", "activated_by", "activated_at"),
}  # fmt: skip
SET_ONCE = {
    "rfqs": ("manifest", "manifest_sha256", "issued_at", "closed_at", "cancelled_at"),
    "quote_versions": ("closed_at", "reviewed_at"),
    "rfq_clarifications": ("answer", "answered_at"),
}
APPEND_ONLY = ("quote_lines", "selections", "rfq_events")


def _upgrade_guards() -> None:
    # Engagements: how each started (ADR-024). Existing rows: LISTED came from a connection,
    # OUTSIDE was recorded by the family. The lifecycle guard is lifted for this backfill only.
    op.execute("ALTER TABLE project_engagements DISABLE TRIGGER project_engagements_lifecycle_only")
    op.execute(
        "UPDATE project_engagements SET origin = CASE party WHEN 'LISTED' THEN 'CONNECTION' "
        "ELSE 'OUTSIDE' END"
    )
    op.execute("ALTER TABLE project_engagements ENABLE TRIGGER project_engagements_lifecycle_only")
    op.alter_column("project_engagements", "origin", nullable=False)
    op.execute(
        "ALTER TABLE project_engagements ADD CONSTRAINT ck_project_engagements_origin "
        "CHECK (origin IN ('CONNECTION', 'OUTSIDE', 'RFQ_SELECTION'))"
    )
    op.execute(
        "ALTER TABLE project_engagements DROP CONSTRAINT ck_project_engagements_party_fields"
    )
    op.execute(
        "ALTER TABLE project_engagements ADD CONSTRAINT ck_project_engagements_party_fields CHECK ("
        "(party = 'LISTED' AND origin = 'CONNECTION' AND profile_id IS NOT NULL "
        "AND connection_id IS NOT NULL AND selection_id IS NULL AND outside_name IS NULL) OR "
        "(party = 'LISTED' AND origin = 'RFQ_SELECTION' AND profile_id IS NOT NULL "
        "AND connection_id IS NULL AND selection_id IS NOT NULL AND outside_name IS NULL "
        "AND family_contact IS NOT NULL) OR "
        "(party = 'OUTSIDE' AND origin = 'OUTSIDE' AND profile_id IS NULL "
        "AND connection_id IS NULL AND selection_id IS NULL AND outside_name IS NOT NULL))"
    )
    # Billing: the substantial-work kinds are a closed set (N-12; QD-02).
    op.execute(
        "ALTER TABLE package_service_usage ADD CONSTRAINT ck_package_service_usage_service "
        "CHECK (service IN ('CONNECTION_ACCEPTED', 'RFQ_SELECTION'))"
    )
    op.execute("ALTER TABLE otp_challenges DROP CONSTRAINT ck_otp_challenges_purpose")
    op.execute(
        "ALTER TABLE otp_challenges ADD CONSTRAINT ck_otp_challenges_purpose CHECK (purpose IN "
        "('LOGIN', 'ACCEPT_BUILD_PLAN', 'SIGN_STRUCTURAL', 'SELECT_QUOTE'))"
    )
    op.execute("ALTER TABLE file_objects DROP CONSTRAINT ck_file_objects_purpose")
    op.execute(
        "ALTER TABLE file_objects ADD CONSTRAINT ck_file_objects_purpose CHECK (purpose IN "
        f"({PURPOSES_BEFORE}, 'QUOTE_ATTACHMENT', 'COMPARISON_DOCUMENT'))"
    )
    # Adjustments change only while their quote version is SUBMITTED with its review open.
    op.execute(
        """
        CREATE FUNCTION p2b_review_open_child() RETURNS trigger LANGUAGE plpgsql AS $$
        DECLARE
            row_data jsonb := CASE WHEN TG_OP = 'DELETE' THEN to_jsonb(OLD) ELSE to_jsonb(NEW) END;
            parent record;
        BEGIN
            SELECT state, review_state INTO parent FROM quote_versions
                WHERE id = (row_data ->> 'quote_version_id')::uuid;
            IF parent.state IS DISTINCT FROM 'SUBMITTED'
               OR parent.review_state NOT IN ('PENDING', 'NEEDS_CLARIFICATION') THEN
                RAISE EXCEPTION 'quote adjustments change only while the review is open';
            END IF;
            IF TG_OP = 'DELETE' THEN RETURN OLD; END IF;
            RETURN NEW;
        END $$;
        """
    )
    op.execute(
        "CREATE TRIGGER quote_adjustments_review_open BEFORE INSERT OR UPDATE OR DELETE ON "
        "quote_adjustments FOR EACH ROW EXECUTE FUNCTION p2b_review_open_child()"
    )
    for table, columns in MUTABLE_COLUMNS.items():
        arguments = ", ".join(f"'{c}'" for c in columns)
        op.execute(
            f"CREATE TRIGGER {table}_lifecycle_only BEFORE UPDATE OR DELETE ON {table} "
            f"FOR EACH ROW EXECUTE FUNCTION p2b_allow_only_columns({arguments})"
        )
    for table, columns in SET_ONCE.items():
        arguments = ", ".join(f"'{c}'" for c in columns)
        op.execute(
            f"CREATE TRIGGER {table}_set_once BEFORE UPDATE ON {table} "
            f"FOR EACH ROW EXECUTE FUNCTION p2b_set_once({arguments})"
        )
    for table in APPEND_ONLY:
        op.execute(
            f"CREATE TRIGGER {table}_append_only BEFORE UPDATE OR DELETE ON {table} "
            "FOR EACH ROW EXECUTE FUNCTION p2b_forbid_mutation()"
        )
    op.execute(
        sa.text(
            "INSERT INTO selection_statements (id, version, text, status, note) "
            "VALUES (CAST(:id AS uuid), 1, :text, 'ACTIVE', :note)"
        ).bindparams(
            id=STATEMENT_V1_ID,
            text=STATEMENT_V1,
            note="Functional wording. IMPLEMENTED / PENDING FINAL CLIENT + LEGAL CONFIRMATION "
            "(Chirag, 2026-10-06, QD-12); replace with the launch-approved wording as a new "
            "version.",
        )
    )
    op.execute(
        """
        DO $$
        BEGIN
            IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'app_rw') THEN
                GRANT SELECT, INSERT, UPDATE ON rfqs, rfq_invitations, quote_versions,
                    rfq_clarifications, comparisons, selection_statements TO app_rw;
                GRANT SELECT, INSERT, UPDATE, DELETE ON quote_drafts, quote_adjustments TO app_rw;
                GRANT SELECT, INSERT ON quote_lines, selections, rfq_events TO app_rw;
            END IF;
        END $$;
        """
    )


def _downgrade_data() -> None:
    """RFQ data goes with the feature. Engagements that started from a selection, and their
    history, are removed with it (their CHECK would fail under 0014); append-only guards are
    lifted for exactly these deletes."""
    for table in ("engagement_events", "document_access_log"):
        op.execute(f"ALTER TABLE {table} DISABLE TRIGGER {table}_append_only")
    op.execute("ALTER TABLE project_engagements DISABLE TRIGGER project_engagements_lifecycle_only")
    op.execute(
        "ALTER TABLE engagement_documents DISABLE TRIGGER engagement_documents_lifecycle_only"
    )
    op.execute("ALTER TABLE selections DISABLE TRIGGER selections_append_only")
    op.execute("DELETE FROM selections")
    op.execute(
        "DELETE FROM engagement_events WHERE subject_id IN "
        "(SELECT id FROM project_engagements WHERE origin = 'RFQ_SELECTION')"
    )
    op.execute(
        "DELETE FROM engagement_documents WHERE engagement_id IN "
        "(SELECT id FROM project_engagements WHERE origin = 'RFQ_SELECTION')"
    )
    op.execute("ALTER TABLE rfq_invitations DISABLE TRIGGER rfq_invitations_lifecycle_only")
    op.execute(
        "DELETE FROM project_engagements WHERE origin = 'RFQ_SELECTION' AND id NOT IN "
        "(SELECT engagement_id FROM rfq_invitations WHERE engagement_id IS NOT NULL)"
    )
    op.execute("ALTER TABLE project_engagements ENABLE TRIGGER project_engagements_lifecycle_only")
    op.execute(
        "ALTER TABLE engagement_documents ENABLE TRIGGER engagement_documents_lifecycle_only"
    )
    op.execute(
        "DELETE FROM document_access_log WHERE file_id IN (SELECT id FROM file_objects WHERE "
        "purpose IN ('QUOTE_ATTACHMENT', 'COMPARISON_DOCUMENT'))"
    )
    for table in ("engagement_events", "document_access_log"):
        op.execute(f"ALTER TABLE {table} ENABLE TRIGGER {table}_append_only")
    op.execute("DELETE FROM package_service_usage WHERE service = 'RFQ_SELECTION'")
    op.execute("ALTER TABLE package_service_usage DROP CONSTRAINT ck_package_service_usage_service")
    op.execute(
        "ALTER TABLE project_engagements DROP CONSTRAINT ck_project_engagements_party_fields"
    )
    op.execute("ALTER TABLE project_engagements DROP CONSTRAINT ck_project_engagements_origin")
    op.execute(
        "ALTER TABLE project_engagements ADD CONSTRAINT ck_project_engagements_party_fields CHECK ("
        "(party = 'LISTED' AND profile_id IS NOT NULL AND connection_id IS NOT NULL "
        "AND outside_name IS NULL) OR "
        "(party = 'OUTSIDE' AND profile_id IS NULL AND connection_id IS NULL "
        "AND outside_name IS NOT NULL))"
    )
    # The tables are dropped next (by the generated commands); their files and codes after.
    op.execute("DROP TRIGGER quote_adjustments_review_open ON quote_adjustments")
    op.execute("DROP FUNCTION p2b_review_open_child()")


def _downgrade_tail() -> None:
    op.execute("DELETE FROM otp_challenges WHERE purpose = 'SELECT_QUOTE'")
    op.execute("ALTER TABLE otp_challenges DROP CONSTRAINT ck_otp_challenges_purpose")
    op.execute(
        "ALTER TABLE otp_challenges ADD CONSTRAINT ck_otp_challenges_purpose CHECK (purpose IN "
        "('LOGIN', 'ACCEPT_BUILD_PLAN', 'SIGN_STRUCTURAL'))"
    )
    op.execute(
        "DELETE FROM file_objects WHERE purpose IN ('QUOTE_ATTACHMENT', 'COMPARISON_DOCUMENT')"
    )
    op.execute("ALTER TABLE file_objects DROP CONSTRAINT ck_file_objects_purpose")
    op.execute(
        "ALTER TABLE file_objects ADD CONSTRAINT ck_file_objects_purpose CHECK (purpose IN "
        f"({PURPOSES_BEFORE}))"
    )
