"""Slice 3.7A: execution (SLICE3_7_READINESS section 0, D, E, M, P.A).

Revision ID: 0016
Revises: 0015
Create Date: 2026-10-06

Stage instances move (EX-03) and are guarded at last (H-09): only their lifecycle columns
change, and no planned date may be written until BP-07A (EX-04). Progress updates and the
execution history are append-only (EX-02, EX-19). Payment marks are append-only information
with no amount column (EX-05). Photos of updates are a new file purpose; a file records the
device's capture claims apart from the image (EX-22).
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0016"
down_revision: str | None = "0015"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "construction_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("stage_instance_id", sa.Uuid(), nullable=False),
        sa.Column("subject", sa.String(length=12), nullable=False),
        sa.Column("from_state", sa.String(length=40), nullable=True),
        sa.Column("to_state", sa.String(length=40), nullable=False),
        sa.Column("actor_user_id", sa.Uuid(), nullable=True),
        sa.Column("actor_role", sa.String(length=12), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column(
            "at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.CheckConstraint(
            "subject IN ('STAGE', 'CONTRACTOR')", name=op.f("ck_construction_events_subject")
        ),
        sa.ForeignKeyConstraint(
            ["actor_user_id"],
            ["users.id"],
            name=op.f("fk_construction_events_actor_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_construction_events_project_id_projects"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["stage_instance_id"],
            ["stage_instances.id"],
            name=op.f("fk_construction_events_stage_instance_id_stage_instances"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_construction_events")),
    )
    op.create_index(
        "ix_construction_events_project", "construction_events", ["project_id", "at"], unique=False
    )
    op.create_table(
        "payment_marks",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("stage_instance_id", sa.Uuid(), nullable=False),
        sa.Column("side", sa.String(length=10), nullable=False),
        sa.Column("value", sa.String(length=3), nullable=False),
        sa.Column("engagement_id", sa.Uuid(), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("marked_by", sa.Uuid(), nullable=False),
        sa.Column("marked_role", sa.String(length=12), nullable=False),
        sa.Column(
            "marked_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.CheckConstraint(
            "(side = 'PAID' AND marked_role = 'FAMILY') OR (side = 'RECEIVED' AND marked_role IN ('PROFESSIONAL', 'OPS', 'ADMIN'))",
            name=op.f("ck_payment_marks_side_role"),
        ),
        sa.CheckConstraint(
            "(side = 'RECEIVED') = (engagement_id IS NOT NULL)",
            name=op.f("ck_payment_marks_engagement"),
        ),
        sa.CheckConstraint(
            "marked_role IN ('FAMILY', 'PROFESSIONAL', 'OPS', 'ADMIN')",
            name=op.f("ck_payment_marks_role"),
        ),
        sa.CheckConstraint("side IN ('PAID', 'RECEIVED')", name=op.f("ck_payment_marks_side")),
        sa.CheckConstraint("value IN ('YES', 'NO')", name=op.f("ck_payment_marks_value")),
        sa.ForeignKeyConstraint(
            ["engagement_id"],
            ["project_engagements.id"],
            name=op.f("fk_payment_marks_engagement_id_project_engagements"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["marked_by"],
            ["users.id"],
            name=op.f("fk_payment_marks_marked_by_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_payment_marks_project_id_projects"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["stage_instance_id"],
            ["stage_instances.id"],
            name=op.f("fk_payment_marks_stage_instance_id_stage_instances"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_payment_marks")),
    )
    op.create_index("ix_payment_marks_project", "payment_marks", ["project_id"], unique=False)
    op.create_index(
        "ix_payment_marks_stage",
        "payment_marks",
        ["stage_instance_id", "side", "marked_at"],
        unique=False,
    )
    op.create_table(
        "stage_updates",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("stage_instance_id", sa.Uuid(), nullable=False),
        sa.Column("engagement_id", sa.Uuid(), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("note", sa.Text(), nullable=False),
        sa.Column("materials", sa.Text(), nullable=True),
        sa.Column("open_problems", sa.Text(), nullable=True),
        sa.Column("file_ids", postgresql.ARRAY(sa.Uuid()), nullable=False),
        sa.Column("corrects_update_id", sa.Uuid(), nullable=True),
        sa.Column("posted_by", sa.Uuid(), nullable=False),
        sa.Column("posted_role", sa.String(length=12), nullable=False),
        sa.Column(
            "posted_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.CheckConstraint(
            "kind IN ('PROGRESS', 'COMPLETION_REQUEST')", name=op.f("ck_stage_updates_kind")
        ),
        sa.CheckConstraint(
            "posted_role IN ('PROFESSIONAL', 'OPS', 'ADMIN')",
            name=op.f("ck_stage_updates_posted_role"),
        ),
        sa.CheckConstraint("cardinality(file_ids) >= 1", name=op.f("ck_stage_updates_has_photos")),
        sa.ForeignKeyConstraint(
            ["corrects_update_id"],
            ["stage_updates.id"],
            name=op.f("fk_stage_updates_corrects_update_id_stage_updates"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["engagement_id"],
            ["project_engagements.id"],
            name=op.f("fk_stage_updates_engagement_id_project_engagements"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["posted_by"],
            ["users.id"],
            name=op.f("fk_stage_updates_posted_by_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_stage_updates_project_id_projects"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["stage_instance_id"],
            ["stage_instances.id"],
            name=op.f("fk_stage_updates_stage_instance_id_stage_instances"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stage_updates")),
    )
    op.create_index(
        "ix_stage_updates_project", "stage_updates", ["project_id", "posted_at"], unique=False
    )
    op.create_index(
        "ix_stage_updates_stage", "stage_updates", ["stage_instance_id", "posted_at"], unique=False
    )
    op.add_column(
        "file_objects",
        sa.Column("capture_claim", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    op.add_column(
        "stage_instances",
        sa.Column("completion_requested_at", sa.DateTime(timezone=True), nullable=True),
    )
    # ### end Alembic commands ###
    op.execute(
        "ALTER TABLE stage_instances ADD CONSTRAINT ck_stage_instances_dates_not_calculated_bp07a "
        "CHECK (planned_start IS NULL AND planned_end IS NULL)"
    )
    op.execute("ALTER TABLE file_objects DROP CONSTRAINT ck_file_objects_purpose")
    op.execute(
        "ALTER TABLE file_objects ADD CONSTRAINT ck_file_objects_purpose CHECK (purpose IN "
        f"({PURPOSES_BEFORE}, 'STAGE_EVIDENCE'))"
    )
    for table, columns in MUTABLE_COLUMNS.items():
        arguments = ", ".join(f"'{c}'" for c in columns)
        op.execute(
            f"CREATE TRIGGER {table}_lifecycle_only BEFORE UPDATE OR DELETE ON {table} "
            f"FOR EACH ROW EXECUTE FUNCTION p2b_allow_only_columns({arguments})"
        )
    for table in APPEND_ONLY:
        op.execute(
            f"CREATE TRIGGER {table}_append_only BEFORE UPDATE OR DELETE ON {table} "
            "FOR EACH ROW EXECUTE FUNCTION p2b_forbid_mutation()"
        )
    op.execute(
        """
        DO $$
        BEGIN
            IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'app_rw') THEN
                GRANT SELECT, INSERT ON stage_updates, construction_events, payment_marks
                    TO app_rw;
            END IF;
        END $$;
        """
    )


def downgrade() -> None:
    """Execution data goes with the feature: stages return to NOT_STARTED and the photos and
    their access log are removed (append-only guards lifted for exactly these deletes)."""
    for table in APPEND_ONLY:
        op.execute(f"DROP TRIGGER {table}_append_only ON {table}")
    op.execute("DROP TRIGGER stage_instances_lifecycle_only ON stage_instances")
    op.execute(
        "UPDATE stage_instances SET state = 'NOT_STARTED', actual_start = NULL, "
        "actual_end = NULL, version = 1 WHERE state <> 'NOT_STARTED' OR actual_start IS NOT NULL"
    )
    op.execute(
        "ALTER TABLE stage_instances DROP CONSTRAINT ck_stage_instances_dates_not_calculated_bp07a"
    )
    op.execute("ALTER TABLE document_access_log DISABLE TRIGGER document_access_log_append_only")
    op.execute(
        "DELETE FROM document_access_log WHERE file_id IN "
        "(SELECT id FROM file_objects WHERE purpose = 'STAGE_EVIDENCE')"
    )
    op.execute("ALTER TABLE document_access_log ENABLE TRIGGER document_access_log_append_only")
    op.execute("DELETE FROM file_objects WHERE purpose = 'STAGE_EVIDENCE'")
    op.execute("ALTER TABLE file_objects DROP CONSTRAINT ck_file_objects_purpose")
    op.execute(
        "ALTER TABLE file_objects ADD CONSTRAINT ck_file_objects_purpose CHECK (purpose IN "
        f"({PURPOSES_BEFORE}))"
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("stage_instances", "completion_requested_at")
    op.drop_column("file_objects", "capture_claim")
    op.drop_index("ix_stage_updates_stage", table_name="stage_updates")
    op.drop_index("ix_stage_updates_project", table_name="stage_updates")
    op.drop_table("stage_updates")
    op.drop_index("ix_payment_marks_stage", table_name="payment_marks")
    op.drop_index("ix_payment_marks_project", table_name="payment_marks")
    op.drop_table("payment_marks")
    op.drop_index("ix_construction_events_project", table_name="construction_events")
    op.drop_table("construction_events")
    # ### end Alembic commands ###


PURPOSES_BEFORE = (
    "'REQUIREMENT_UPLOAD', 'AI_CONCEPT', 'VERIFICATION_EVIDENCE', 'PORTFOLIO', 'INVOICE', "
    "'QUOTE_DOCUMENT', 'DRAWING', 'BUILD_PLAN_EVIDENCE', 'BUILD_PLAN_DOCUMENT', "
    "'QUOTE_ATTACHMENT', 'COMPARISON_DOCUMENT'"
)
# Copies of the models' guard lists as they stand in this revision.
MUTABLE_COLUMNS = {
    "stage_instances": (
        "state", "gate_status", "actual_start", "actual_end", "completion_requested_at",
        "updated_at", "version",
    ),
}  # fmt: skip
APPEND_ONLY = ("stage_updates", "construction_events", "payment_marks")
