"""Slice 3.7B: assurance (SLICE3_7_READINESS section 0, F, G, K, P.B, P.C).

Revision ID: 0017
Revises: 0016
Create Date: 2026-10-06

Auditor appointments with a unique auditor ID (EX-09), versioned gate checklists (EX-08) with
version 1 seeded from the S04 "verified at" mapping for Gates 1 to 5, one live initial inspection
per gate stage instance (EX-07), checkpoint results editable only while their inspection is in
progress, inspections frozen from submission, findings whose text never changes and that close
only through a re-inspection (EX-11), immutable reports and test results, an append-only history.
New file purposes INSPECTION_EVIDENCE and INSPECTION_REPORT, the SUBMIT_INSPECTION confirmation,
and gate changes recorded in the execution history (subject GATE).
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0017"
down_revision: str | None = "0016"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "checklist_versions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.SmallInteger(), nullable=False),
        sa.Column("status", sa.String(length=10), nullable=False),
        sa.Column("note", sa.Text(), nullable=False),
        sa.Column("prepared_by", sa.Uuid(), nullable=True),
        sa.Column("published_by", sa.Uuid(), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('DRAFT', 'PUBLISHED', 'RETIRED')", name=op.f("ck_checklist_versions_status")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_checklist_versions")),
        sa.UniqueConstraint("version", name=op.f("uq_checklist_versions_version")),
    )
    op.create_index(
        "uq_checklist_versions_one_published",
        "checklist_versions",
        ["status"],
        unique=True,
        postgresql_where=sa.text("status = 'PUBLISHED'"),
    )
    op.create_table(
        "assurance_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=True),
        sa.Column("subject", sa.String(length=20), nullable=False),
        sa.Column("subject_id", sa.Uuid(), nullable=False),
        sa.Column("from_state", sa.String(length=30), nullable=True),
        sa.Column("to_state", sa.String(length=30), nullable=False),
        sa.Column("actor_user_id", sa.Uuid(), nullable=True),
        sa.Column("actor_role", sa.String(length=12), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("detail", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "file_ids", postgresql.ARRAY(sa.Uuid()), server_default=sa.text("'{}'"), nullable=False
        ),
        sa.Column(
            "at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.CheckConstraint(
            "subject IN ('APPOINTMENT', 'CHECKLIST', 'INSPECTION', 'NON_CONFORMANCE')",
            name=op.f("ck_assurance_events_subject"),
        ),
        sa.ForeignKeyConstraint(
            ["actor_user_id"],
            ["users.id"],
            name=op.f("fk_assurance_events_actor_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_assurance_events_project_id_projects"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_assurance_events")),
    )
    op.create_index(
        "ix_assurance_events_project", "assurance_events", ["project_id", "at"], unique=False
    )
    op.create_index(
        "ix_assurance_events_subject", "assurance_events", ["subject_id", "at"], unique=False
    )
    op.create_table(
        "checkpoints",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("checklist_version_id", sa.Uuid(), nullable=False),
        sa.Column("gate", sa.SmallInteger(), nullable=False),
        sa.Column("sequence", sa.SmallInteger(), nullable=False),
        sa.Column("code", sa.String(length=20), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("expected_evidence", sa.String(length=200), nullable=True),
        sa.Column("is_critical", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("spec_line_code", sa.String(length=3), nullable=True),
        sa.CheckConstraint("gate BETWEEN 1 AND 6", name=op.f("ck_checkpoints_gate")),
        sa.ForeignKeyConstraint(
            ["checklist_version_id"],
            ["checklist_versions.id"],
            name=op.f("fk_checkpoints_checklist_version_id_checklist_versions"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_checkpoints")),
        sa.UniqueConstraint(
            "checklist_version_id", "code", name=op.f("uq_checkpoints_checklist_version_id_code")
        ),
        sa.UniqueConstraint(
            "checklist_version_id",
            "gate",
            "sequence",
            name=op.f("uq_checkpoints_checklist_version_id_gate_sequence"),
        ),
    )
    op.create_table(
        "auditor_appointments",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("auditor_code", sa.String(length=20), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("qualification", sa.String(length=300), nullable=False),
        sa.Column("registration_reference", sa.String(length=120), nullable=True),
        sa.Column("credential_file_id", sa.Uuid(), nullable=True),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("status", sa.String(length=10), nullable=False),
        sa.Column("appointed_by", sa.Uuid(), nullable=False),
        sa.Column("ended_by", sa.Uuid(), nullable=True),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("end_reason", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(status = 'ENDED') = (ended_at IS NOT NULL AND end_reason IS NOT NULL)",
            name=op.f("ck_auditor_appointments_ended"),
        ),
        sa.CheckConstraint(
            "status IN ('ACTIVE', 'ENDED')", name=op.f("ck_auditor_appointments_status")
        ),
        sa.ForeignKeyConstraint(
            ["appointed_by"],
            ["users.id"],
            name=op.f("fk_auditor_appointments_appointed_by_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["credential_file_id"],
            ["file_objects.id"],
            name=op.f("fk_auditor_appointments_credential_file_id_file_objects"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["ended_by"],
            ["users.id"],
            name=op.f("fk_auditor_appointments_ended_by_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_auditor_appointments_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_auditor_appointments")),
        sa.UniqueConstraint("auditor_code", name=op.f("uq_auditor_appointments_auditor_code")),
    )
    op.create_index(
        "uq_auditor_appointments_active_user",
        "auditor_appointments",
        ["user_id"],
        unique=True,
        postgresql_where=sa.text("status = 'ACTIVE' AND user_id IS NOT NULL"),
    )
    op.create_table(
        "inspections",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("stage_instance_id", sa.Uuid(), nullable=False),
        sa.Column("gate", sa.SmallInteger(), nullable=False),
        sa.Column("kind", sa.String(length=15), nullable=False),
        sa.Column("appointment_id", sa.Uuid(), nullable=False),
        sa.Column("checklist_version_id", sa.Uuid(), nullable=False),
        sa.Column("amends_id", sa.Uuid(), nullable=True),
        sa.Column("reinspects_id", sa.Uuid(), nullable=True),
        sa.Column(
            "nc_ids", postgresql.ARRAY(sa.Uuid()), server_default=sa.text("'{}'"), nullable=False
        ),
        sa.Column("state", sa.String(length=15), nullable=False),
        sa.Column("visit_note", sa.Text(), nullable=True),
        sa.Column("scheduled_by", sa.Uuid(), nullable=False),
        sa.Column(
            "scheduled_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("readiness_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("submitted_by", sa.Uuid(), nullable=True),
        sa.Column("submitted_role", sa.String(length=12), nullable=True),
        sa.Column("submit_challenge_id", sa.Uuid(), nullable=True),
        sa.Column("staff_capture", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("capture_evidence_file_id", sa.Uuid(), nullable=True),
        sa.Column("content_sha256", sa.String(length=64), nullable=True),
        sa.Column("approved_by", sa.Uuid(), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("return_reason", sa.Text(), nullable=True),
        sa.Column("cancel_reason", sa.String(length=20), nullable=True),
        sa.Column("cancel_note", sa.Text(), nullable=True),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(kind = 'REINSPECTION') = (cardinality(nc_ids) > 0)",
            name=op.f("ck_inspections_reinspection_set"),
        ),
        sa.CheckConstraint(
            "cancel_reason IS NULL OR cancel_reason IN ('OPERATIONS', 'PACKAGE_ENDED', 'PROJECT_CLOSED')",
            name=op.f("ck_inspections_cancel_reason_values"),
        ),
        sa.CheckConstraint("kind IN ('INITIAL', 'REINSPECTION')", name=op.f("ck_inspections_kind")),
        sa.CheckConstraint(
            "state <> 'CANCELLED' OR cancel_reason IS NOT NULL",
            name=op.f("ck_inspections_cancelled_reason"),
        ),
        sa.CheckConstraint(
            "state <> 'RETURNED' OR return_reason IS NOT NULL",
            name=op.f("ck_inspections_returned_reason"),
        ),
        sa.CheckConstraint(
            "state IN ('SCHEDULED', 'IN_PROGRESS', 'SUBMITTED', 'APPROVED', 'RETURNED', 'CANCELLED')",
            name=op.f("ck_inspections_state"),
        ),
        sa.CheckConstraint(
            "state NOT IN ('SUBMITTED', 'APPROVED', 'RETURNED') OR (content_sha256 IS NOT NULL AND submitted_at IS NOT NULL)",
            name=op.f("ck_inspections_submitted_is_hashed"),
        ),
        sa.CheckConstraint(
            "NOT staff_capture OR capture_evidence_file_id IS NOT NULL",
            name=op.f("ck_inspections_capture_has_evidence"),
        ),
        sa.CheckConstraint("gate BETWEEN 1 AND 6", name=op.f("ck_inspections_gate")),
        sa.ForeignKeyConstraint(
            ["amends_id"],
            ["inspections.id"],
            name=op.f("fk_inspections_amends_id_inspections"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["appointment_id"],
            ["auditor_appointments.id"],
            name=op.f("fk_inspections_appointment_id_auditor_appointments"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["approved_by"],
            ["users.id"],
            name=op.f("fk_inspections_approved_by_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["capture_evidence_file_id"],
            ["file_objects.id"],
            name=op.f("fk_inspections_capture_evidence_file_id_file_objects"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["checklist_version_id"],
            ["checklist_versions.id"],
            name=op.f("fk_inspections_checklist_version_id_checklist_versions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_inspections_project_id_projects"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["reinspects_id"],
            ["inspections.id"],
            name=op.f("fk_inspections_reinspects_id_inspections"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["scheduled_by"],
            ["users.id"],
            name=op.f("fk_inspections_scheduled_by_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["stage_instance_id"],
            ["stage_instances.id"],
            name=op.f("fk_inspections_stage_instance_id_stage_instances"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["submitted_by"],
            ["users.id"],
            name=op.f("fk_inspections_submitted_by_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_inspections")),
        sa.UniqueConstraint("submit_challenge_id", name=op.f("uq_inspections_submit_challenge_id")),
    )
    op.create_index(
        "ix_inspections_appointment_state", "inspections", ["appointment_id", "state"], unique=False
    )
    op.create_index(
        "ix_inspections_project", "inspections", ["project_id", "created_at"], unique=False
    )
    op.create_index(
        "uq_inspections_one_initial",
        "inspections",
        ["stage_instance_id"],
        unique=True,
        postgresql_where=sa.text("kind = 'INITIAL' AND state NOT IN ('RETURNED', 'CANCELLED')"),
    )
    op.create_table(
        "inspection_reports",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("inspection_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.SmallInteger(), nullable=False),
        sa.Column("file_id", sa.Uuid(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("correction_reason", sa.Text(), nullable=True),
        sa.Column("rendered_by", sa.Uuid(), nullable=False),
        sa.Column(
            "rendered_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(version = 1) = (correction_reason IS NULL)",
            name=op.f("ck_inspection_reports_correction_reason"),
        ),
        sa.ForeignKeyConstraint(
            ["file_id"],
            ["file_objects.id"],
            name=op.f("fk_inspection_reports_file_id_file_objects"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["inspection_id"],
            ["inspections.id"],
            name=op.f("fk_inspection_reports_inspection_id_inspections"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_inspection_reports_project_id_projects"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["rendered_by"],
            ["users.id"],
            name=op.f("fk_inspection_reports_rendered_by_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_inspection_reports")),
        sa.UniqueConstraint(
            "inspection_id", "version", name=op.f("uq_inspection_reports_inspection_id_version")
        ),
    )
    op.create_table(
        "inspection_results",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("inspection_id", sa.Uuid(), nullable=False),
        sa.Column("checkpoint_id", sa.Uuid(), nullable=False),
        sa.Column("result", sa.String(length=20), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("na_reason", sa.Text(), nullable=True),
        sa.Column("measurement", sa.Text(), nullable=True),
        sa.Column("room_tag", sa.String(length=80), nullable=True),
        sa.Column(
            "file_ids", postgresql.ARRAY(sa.Uuid()), server_default=sa.text("'{}'"), nullable=False
        ),
        sa.Column("severity", sa.String(length=10), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("corrective_action", sa.Text(), nullable=True),
        sa.Column("due_date", sa.Date(), nullable=True),
        sa.CheckConstraint(
            "result <> 'NOT_APPLICABLE' OR na_reason IS NOT NULL",
            name=op.f("ck_inspection_results_na_reason"),
        ),
        sa.CheckConstraint(
            "result IN ('PASS', 'OBSERVATION', 'NON_CONFORMANCE', 'NOT_APPLICABLE')",
            name=op.f("ck_inspection_results_result"),
        ),
        sa.CheckConstraint(
            "severity IS NULL OR result = 'NON_CONFORMANCE'",
            name=op.f("ck_inspection_results_finding_is_nc"),
        ),
        sa.CheckConstraint(
            "severity IS NULL OR severity IN ('MINOR', 'MAJOR', 'CRITICAL')",
            name=op.f("ck_inspection_results_severity"),
        ),
        sa.CheckConstraint(
            "(severity IS NOT NULL) = (description IS NOT NULL AND corrective_action IS NOT NULL AND due_date IS NOT NULL)",
            name=op.f("ck_inspection_results_finding_complete"),
        ),
        sa.ForeignKeyConstraint(
            ["checkpoint_id"],
            ["checkpoints.id"],
            name=op.f("fk_inspection_results_checkpoint_id_checkpoints"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["inspection_id"],
            ["inspections.id"],
            name=op.f("fk_inspection_results_inspection_id_inspections"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_inspection_results")),
        sa.UniqueConstraint(
            "inspection_id",
            "checkpoint_id",
            name=op.f("uq_inspection_results_inspection_id_checkpoint_id"),
        ),
    )
    op.create_table(
        "non_conformances",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("stage_instance_id", sa.Uuid(), nullable=False),
        sa.Column("inspection_id", sa.Uuid(), nullable=False),
        sa.Column("result_id", sa.Uuid(), nullable=False),
        sa.Column("checkpoint_id", sa.Uuid(), nullable=False),
        sa.Column("severity", sa.String(length=10), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("corrective_action", sa.Text(), nullable=False),
        sa.Column("engagement_id", sa.Uuid(), nullable=True),
        sa.Column("due_date", sa.Date(), nullable=False),
        sa.Column("state", sa.String(length=25), nullable=False),
        sa.Column("closed_by_inspection_id", sa.Uuid(), nullable=True),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(state = 'CLOSED') = (closed_by_inspection_id IS NOT NULL AND closed_at IS NOT NULL)",
            name=op.f("ck_non_conformances_closed_by_reinspection"),
        ),
        sa.CheckConstraint(
            "severity IN ('MINOR', 'MAJOR', 'CRITICAL')", name=op.f("ck_non_conformances_severity")
        ),
        sa.CheckConstraint(
            "state IN ('OPEN', 'RECTIFICATION_SUBMITTED', 'REINSPECTION_SCHEDULED', 'CLOSED')",
            name=op.f("ck_non_conformances_state"),
        ),
        sa.ForeignKeyConstraint(
            ["checkpoint_id"],
            ["checkpoints.id"],
            name=op.f("fk_non_conformances_checkpoint_id_checkpoints"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["closed_by_inspection_id"],
            ["inspections.id"],
            name=op.f("fk_non_conformances_closed_by_inspection_id_inspections"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["engagement_id"],
            ["project_engagements.id"],
            name=op.f("fk_non_conformances_engagement_id_project_engagements"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["inspection_id"],
            ["inspections.id"],
            name=op.f("fk_non_conformances_inspection_id_inspections"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_non_conformances_project_id_projects"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["result_id"],
            ["inspection_results.id"],
            name=op.f("fk_non_conformances_result_id_inspection_results"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["stage_instance_id"],
            ["stage_instances.id"],
            name=op.f("fk_non_conformances_stage_instance_id_stage_instances"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_non_conformances")),
        sa.UniqueConstraint("result_id", name=op.f("uq_non_conformances_result_id")),
    )
    op.create_index(
        "ix_non_conformances_project_state",
        "non_conformances",
        ["project_id", "state"],
        unique=False,
    )
    op.create_index(
        "ix_non_conformances_stage", "non_conformances", ["stage_instance_id"], unique=False
    )
    op.create_table(
        "test_results",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("result_id", sa.Uuid(), nullable=False),
        sa.Column("test_kind", sa.String(length=120), nullable=False),
        sa.Column("value", sa.Text(), nullable=False),
        sa.Column("file_id", sa.Uuid(), nullable=True),
        sa.Column("recorded_by", sa.Uuid(), nullable=False),
        sa.Column("recorded_role", sa.String(length=12), nullable=False),
        sa.Column(
            "recorded_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["file_id"],
            ["file_objects.id"],
            name=op.f("fk_test_results_file_id_file_objects"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_test_results_project_id_projects"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["recorded_by"],
            ["users.id"],
            name=op.f("fk_test_results_recorded_by_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["result_id"],
            ["inspection_results.id"],
            name=op.f("fk_test_results_result_id_inspection_results"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_test_results")),
    )
    # ### end Alembic commands ###
    _upgrade_guards()


def _upgrade_guards() -> None:
    op.execute("CREATE SEQUENCE auditor_code_seq START 1")
    op.execute("ALTER TABLE file_objects DROP CONSTRAINT ck_file_objects_purpose")
    op.execute(
        "ALTER TABLE file_objects ADD CONSTRAINT ck_file_objects_purpose CHECK (purpose IN "
        f"({PURPOSES_BEFORE}, 'INSPECTION_EVIDENCE', 'INSPECTION_REPORT'))"
    )
    op.execute("ALTER TABLE otp_challenges DROP CONSTRAINT ck_otp_challenges_purpose")
    op.execute(
        "ALTER TABLE otp_challenges ADD CONSTRAINT ck_otp_challenges_purpose CHECK (purpose IN "
        f"({OTP_BEFORE}, 'SUBMIT_INSPECTION'))"
    )
    op.execute("ALTER TABLE construction_events DROP CONSTRAINT ck_construction_events_subject")
    op.execute(
        "ALTER TABLE construction_events ADD CONSTRAINT ck_construction_events_subject "
        "CHECK (subject IN ('STAGE', 'CONTRACTOR', 'GATE'))"
    )
    # EX-08: version 1 holds Gates 1 to 5 from S04's "verified at" column; the test it names
    # (cube test, mill test certificate, ...) becomes the expected evidence. Gate 6 is drafted
    # by the auditor and operations and published by ADMIN as a later version.
    op.execute(
        sa.text(
            "INSERT INTO checklist_versions (id, version, status, note) "
            "VALUES (CAST(:id AS uuid), 1, 'DRAFT', :note)"
        ).bindparams(id=CHECKLIST_V1_ID, note=CHECKLIST_V1_NOTE)
    )
    op.execute(
        sa.text(
            """
            INSERT INTO checkpoints (id, checklist_version_id, gate, sequence, code, text,
                expected_evidence, is_critical, spec_line_code)
            SELECT gen_random_uuid(), CAST(:id AS uuid), g.gate,
                row_number() OVER (PARTITION BY g.gate ORDER BY m.sequence),
                'G' || g.gate || '-' || m.code, m.item,
                NULLIF(btrim(regexp_replace(m.verified_at, '^Gate [1-5][ ,+]*', '')), ''),
                false, m.code
            FROM spec_line_masters m
            CROSS JOIN LATERAL (
                SELECT CAST(substring(m.verified_at FROM '^Gate ([1-5])') AS smallint) AS gate
            ) g
            WHERE g.gate IS NOT NULL
            """
        ).bindparams(id=CHECKLIST_V1_ID)
    )
    op.execute(
        sa.text(
            "UPDATE checklist_versions SET status = 'PUBLISHED', published_at = now() "
            "WHERE id = CAST(:id AS uuid)"
        ).bindparams(id=CHECKLIST_V1_ID)
    )
    # Checkpoints change only while their checklist is DRAFT; results only while their
    # inspection is IN_PROGRESS.
    op.execute(
        "CREATE TRIGGER checkpoints_draft_only BEFORE INSERT OR UPDATE OR DELETE ON checkpoints "
        "FOR EACH ROW EXECUTE FUNCTION "
        "p2b_status_child_editable('checklist_versions', 'checklist_version_id', 'DRAFT')"
    )
    op.execute(
        "CREATE TRIGGER inspection_results_open_only BEFORE INSERT OR UPDATE OR DELETE ON "
        "inspection_results FOR EACH ROW EXECUTE FUNCTION "
        "p2b_child_editable('inspections', 'inspection_id', 'IN_PROGRESS')"
    )
    # An inspection's content is frozen from submission (BR-123): after SUBMITTED only the
    # decision columns move; terminal states never change.
    op.execute(
        """
        CREATE FUNCTION p2b_inspection_frozen() RETURNS trigger LANGUAGE plpgsql AS $$
        DECLARE
            frozen text[] := ARRAY['summary', 'submitted_at', 'submitted_by', 'submitted_role',
                'submit_challenge_id', 'staff_capture', 'capture_evidence_file_id',
                'content_sha256', 'readiness_at'];
            col text;
        BEGIN
            IF OLD.state IN ('SUBMITTED', 'APPROVED', 'RETURNED', 'CANCELLED') THEN
                FOREACH col IN ARRAY frozen LOOP
                    IF (to_jsonb(NEW) -> col) IS DISTINCT FROM (to_jsonb(OLD) -> col) THEN
                        RAISE EXCEPTION 'inspection % is frozen (%)', OLD.id, col;
                    END IF;
                END LOOP;
            END IF;
            IF OLD.state IN ('APPROVED', 'RETURNED', 'CANCELLED')
               AND NEW.state IS DISTINCT FROM OLD.state THEN
                RAISE EXCEPTION 'inspection % is in a terminal state', OLD.id;
            END IF;
            RETURN NEW;
        END $$;
        """
    )
    op.execute(
        "CREATE TRIGGER inspections_frozen BEFORE UPDATE ON inspections "
        "FOR EACH ROW EXECUTE FUNCTION p2b_inspection_frozen()"
    )
    for table, columns in MUTABLE_COLUMNS.items():
        arguments = ", ".join(f"'{c}'" for c in columns)
        op.execute(
            f"CREATE TRIGGER {table}_lifecycle_only BEFORE UPDATE OR DELETE ON {table} "
            f"FOR EACH ROW EXECUTE FUNCTION p2b_allow_only_columns({arguments})"
        )
    for table in APPEND_ONLY:
        op.execute(
            f"CREATE TRIGGER {table}_append_only BEFORE UPDATE OR DELETE ON {table} "
            "FOR EACH ROW EXECUTE FUNCTION p2b_forbid_mutation()"
        )
    op.execute(
        """
        DO $$
        BEGIN
            IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'app_rw') THEN
                GRANT SELECT, INSERT, UPDATE ON auditor_appointments, checklist_versions,
                    inspections, non_conformances TO app_rw;
                GRANT SELECT, INSERT, UPDATE, DELETE ON checkpoints, inspection_results TO app_rw;
                GRANT SELECT, INSERT ON inspection_reports, test_results, assurance_events
                    TO app_rw;
                GRANT USAGE ON SEQUENCE auditor_code_seq TO app_rw;
            END IF;
        END $$;
        """
    )


def downgrade() -> None:
    """Assurance data goes with the feature: gate statuses return to NOT_INSPECTED, GATE history
    rows and the feature's files and codes are removed (guards lifted for exactly these
    changes); the tables are dropped by the generated commands."""
    op.execute("DROP TRIGGER inspections_frozen ON inspections")
    op.execute("DROP FUNCTION p2b_inspection_frozen()")
    op.execute("ALTER TABLE stage_instances DISABLE TRIGGER stage_instances_lifecycle_only")
    op.execute("UPDATE stage_instances SET gate_status = 'NOT_INSPECTED' WHERE is_gate")
    op.execute("ALTER TABLE stage_instances ENABLE TRIGGER stage_instances_lifecycle_only")
    op.execute("ALTER TABLE construction_events DISABLE TRIGGER construction_events_append_only")
    op.execute("DELETE FROM construction_events WHERE subject = 'GATE'")
    op.execute("ALTER TABLE construction_events ENABLE TRIGGER construction_events_append_only")
    op.execute("ALTER TABLE construction_events DROP CONSTRAINT ck_construction_events_subject")
    op.execute(
        "ALTER TABLE construction_events ADD CONSTRAINT ck_construction_events_subject "
        "CHECK (subject IN ('STAGE', 'CONTRACTOR'))"
    )
    _downgrade_tables()
    op.execute("ALTER TABLE document_access_log DISABLE TRIGGER document_access_log_append_only")
    op.execute(
        "DELETE FROM document_access_log WHERE file_id IN (SELECT id FROM file_objects WHERE "
        "purpose IN ('INSPECTION_EVIDENCE', 'INSPECTION_REPORT'))"
    )
    op.execute("ALTER TABLE document_access_log ENABLE TRIGGER document_access_log_append_only")
    op.execute(
        "DELETE FROM file_objects WHERE purpose IN ('INSPECTION_EVIDENCE', 'INSPECTION_REPORT')"
    )
    op.execute("ALTER TABLE file_objects DROP CONSTRAINT ck_file_objects_purpose")
    op.execute(
        "ALTER TABLE file_objects ADD CONSTRAINT ck_file_objects_purpose CHECK (purpose IN "
        f"({PURPOSES_BEFORE}))"
    )
    op.execute("DELETE FROM otp_challenges WHERE purpose = 'SUBMIT_INSPECTION'")
    op.execute("ALTER TABLE otp_challenges DROP CONSTRAINT ck_otp_challenges_purpose")
    op.execute(
        "ALTER TABLE otp_challenges ADD CONSTRAINT ck_otp_challenges_purpose CHECK (purpose IN "
        f"({OTP_BEFORE}))"
    )
    op.execute("DROP SEQUENCE auditor_code_seq")


def _downgrade_tables() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("test_results")
    op.drop_index("ix_non_conformances_stage", table_name="non_conformances")
    op.drop_index("ix_non_conformances_project_state", table_name="non_conformances")
    op.drop_table("non_conformances")
    op.drop_table("inspection_results")
    op.drop_table("inspection_reports")
    op.drop_index(
        "uq_inspections_one_initial",
        table_name="inspections",
        postgresql_where=sa.text("kind = 'INITIAL' AND state NOT IN ('RETURNED', 'CANCELLED')"),
    )
    op.drop_index("ix_inspections_project", table_name="inspections")
    op.drop_index("ix_inspections_appointment_state", table_name="inspections")
    op.drop_table("inspections")
    op.drop_index(
        "uq_auditor_appointments_active_user",
        table_name="auditor_appointments",
        postgresql_where=sa.text("status = 'ACTIVE' AND user_id IS NOT NULL"),
    )
    op.drop_table("auditor_appointments")
    op.drop_table("checkpoints")
    op.drop_index("ix_assurance_events_subject", table_name="assurance_events")
    op.drop_index("ix_assurance_events_project", table_name="assurance_events")
    op.drop_table("assurance_events")
    op.drop_index(
        "uq_checklist_versions_one_published",
        table_name="checklist_versions",
        postgresql_where=sa.text("status = 'PUBLISHED'"),
    )
    op.drop_table("checklist_versions")
    # ### end Alembic commands ###


PURPOSES_BEFORE = (
    "'REQUIREMENT_UPLOAD', 'AI_CONCEPT', 'VERIFICATION_EVIDENCE', 'PORTFOLIO', 'INVOICE', "
    "'QUOTE_DOCUMENT', 'DRAWING', 'BUILD_PLAN_EVIDENCE', 'BUILD_PLAN_DOCUMENT', "
    "'QUOTE_ATTACHMENT', 'COMPARISON_DOCUMENT', 'STAGE_EVIDENCE'"
)
OTP_BEFORE = "'LOGIN', 'ACCEPT_BUILD_PLAN', 'SIGN_STRUCTURAL', 'SELECT_QUOTE'"
CHECKLIST_V1_ID = "37000000-0000-7000-8000-000000000001"
CHECKLIST_V1_NOTE = (
    "Version 1 (EX-08): Gates 1 to 5 from the S04 'verified at' mapping; the criteria are each "
    "line's issued specification and the project's accepted value. Gate 6 is drafted by the "
    "auditor and operations and published by ADMIN. S04 also maps C24 (External works) to Gate 6."
)
# Copies of the models' guard lists as they stand in this revision.
MUTABLE_COLUMNS = {
    "auditor_appointments": ("status", "ended_by", "ended_at", "end_reason", "updated_at"),
    "checklist_versions": ("status", "note", "published_by", "published_at", "updated_at"),
    "inspections": (
        "state", "readiness_at", "summary", "submitted_at", "submitted_by", "submitted_role",
        "submit_challenge_id", "staff_capture", "capture_evidence_file_id", "content_sha256",
        "approved_by", "approved_at", "return_reason", "cancel_reason", "cancel_note",
        "updated_at", "version",
    ),
    "non_conformances": (
        "state", "due_date", "closed_by_inspection_id", "closed_at", "updated_at", "version",
    ),
}  # fmt: skip
APPEND_ONLY = ("assurance_events", "test_results", "inspection_reports")
