"""Slice 3.7C: handover and Build Record (SLICE3_7_READINESS section 0, H, I, K, P.D, P.E).

Revision ID: 0018
Revises: 0017
Create Date: 2026-10-06

One handover per project, frozen once acknowledged or issued by operations (EX-15: an operations
issue carries actor, time and reason and is never an acknowledgement, CHECK); documents and
warranties change only while the handover is OPEN; the acknowledgement statement is versioned
configuration with version 1 seeded ACTIVE as functional wording (IMPLEMENTED / PENDING FINAL
CLIENT + LEGAL CONFIRMATION); Build Record versions are frozen from ISSUED and only move to
SUPERSEDED (EX-17); history is append-only. New file purposes HANDOVER_DOCUMENT,
BUILD_RECORD_DOCUMENT and BUILD_RECORD_EXPORT, and the ACKNOWLEDGE_HANDOVER confirmation.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0018"
down_revision: str | None = "0017"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "acknowledgement_statements",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=10), nullable=False),
        sa.Column("note", sa.Text(), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("activated_by", sa.Uuid(), nullable=True),
        sa.Column("activated_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status IN ('DRAFT', 'ACTIVE', 'RETIRED')",
            name=op.f("ck_acknowledgement_statements_status"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_acknowledgement_statements")),
        sa.UniqueConstraint("version", name=op.f("uq_acknowledgement_statements_version")),
    )
    op.create_index(
        "uq_acknowledgement_statements_one_active",
        "acknowledgement_statements",
        ["status"],
        unique=True,
        postgresql_where=sa.text("status = 'ACTIVE'"),
    )
    op.create_table(
        "handovers",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("state", sa.String(length=25), nullable=False),
        sa.Column("opened_by", sa.Uuid(), nullable=False),
        sa.Column(
            "opened_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("ready_by", sa.Uuid(), nullable=True),
        sa.Column("ready_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("acknowledged_by", sa.Uuid(), nullable=True),
        sa.Column("acknowledged_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("challenge_id", sa.Uuid(), nullable=True),
        sa.Column("statement_id", sa.Uuid(), nullable=True),
        sa.Column("statement_text", sa.Text(), nullable=True),
        sa.Column("forced_by", sa.Uuid(), nullable=True),
        sa.Column("forced_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("forced_reason", sa.Text(), nullable=True),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "state <> 'ACKNOWLEDGED' OR (acknowledged_by IS NOT NULL AND acknowledged_at IS NOT NULL AND challenge_id IS NOT NULL AND statement_id IS NOT NULL AND statement_text IS NOT NULL)",
            name=op.f("ck_handovers_acknowledged_complete"),
        ),
        sa.CheckConstraint(
            "state <> 'ISSUED_BY_OPERATIONS' OR (forced_by IS NOT NULL AND forced_at IS NOT NULL AND forced_reason IS NOT NULL AND acknowledged_by IS NULL AND challenge_id IS NULL)",
            name=op.f("ck_handovers_forced_is_not_acknowledgement"),
        ),
        sa.CheckConstraint(
            "state IN ('OPEN', 'READY', 'ACKNOWLEDGED', 'ISSUED_BY_OPERATIONS')",
            name=op.f("ck_handovers_state"),
        ),
        sa.ForeignKeyConstraint(
            ["acknowledged_by"],
            ["users.id"],
            name=op.f("fk_handovers_acknowledged_by_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["forced_by"],
            ["users.id"],
            name=op.f("fk_handovers_forced_by_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["opened_by"],
            ["users.id"],
            name=op.f("fk_handovers_opened_by_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_handovers_project_id_projects"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["ready_by"],
            ["users.id"],
            name=op.f("fk_handovers_ready_by_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["statement_id"],
            ["acknowledgement_statements.id"],
            name=op.f("fk_handovers_statement_id_acknowledgement_statements"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_handovers")),
        sa.UniqueConstraint("challenge_id", name=op.f("uq_handovers_challenge_id")),
        sa.UniqueConstraint("project_id", name=op.f("uq_handovers_project_id")),
    )
    op.create_table(
        "records_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("subject", sa.String(length=15), nullable=False),
        sa.Column("subject_id", sa.Uuid(), nullable=False),
        sa.Column("from_state", sa.String(length=25), nullable=True),
        sa.Column("to_state", sa.String(length=25), nullable=False),
        sa.Column("actor_user_id", sa.Uuid(), nullable=True),
        sa.Column("actor_role", sa.String(length=12), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("detail", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.CheckConstraint(
            "subject IN ('HANDOVER', 'BUILD_RECORD')", name=op.f("ck_records_events_subject")
        ),
        sa.ForeignKeyConstraint(
            ["actor_user_id"],
            ["users.id"],
            name=op.f("fk_records_events_actor_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_records_events_project_id_projects"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_records_events")),
    )
    op.create_index(
        "ix_records_events_project", "records_events", ["project_id", "at"], unique=False
    )
    op.create_table(
        "build_records",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("handover_id", sa.Uuid(), nullable=False),
        sa.Column("version_no", sa.SmallInteger(), nullable=False),
        sa.Column("state", sa.String(length=10), nullable=False),
        sa.Column("basis", sa.String(length=25), nullable=False),
        sa.Column("snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("snapshot_sha256", sa.String(length=64), nullable=True),
        sa.Column("pdf_file_id", sa.Uuid(), nullable=True),
        sa.Column("pdf_sha256", sa.String(length=64), nullable=True),
        sa.Column("json_file_id", sa.Uuid(), nullable=True),
        sa.Column("json_sha256", sa.String(length=64), nullable=True),
        sa.Column("correction_reason", sa.Text(), nullable=True),
        sa.Column("assembled_by_role", sa.String(length=12), nullable=False),
        sa.Column("issued_by", sa.Uuid(), nullable=True),
        sa.Column("issued_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "basis IN ('ACKNOWLEDGED', 'ISSUED_BY_OPERATIONS')", name=op.f("ck_build_records_basis")
        ),
        sa.CheckConstraint(
            "state = 'DRAFT' OR (snapshot_sha256 IS NOT NULL AND pdf_file_id IS NOT NULL AND json_file_id IS NOT NULL AND issued_at IS NOT NULL)",
            name=op.f("ck_build_records_issued_complete"),
        ),
        sa.CheckConstraint(
            "state IN ('DRAFT', 'ISSUED', 'SUPERSEDED')", name=op.f("ck_build_records_state")
        ),
        sa.CheckConstraint(
            "(version_no = 1) = (correction_reason IS NULL)",
            name=op.f("ck_build_records_correction_reason"),
        ),
        sa.ForeignKeyConstraint(
            ["handover_id"],
            ["handovers.id"],
            name=op.f("fk_build_records_handover_id_handovers"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["issued_by"],
            ["users.id"],
            name=op.f("fk_build_records_issued_by_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["json_file_id"],
            ["file_objects.id"],
            name=op.f("fk_build_records_json_file_id_file_objects"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["pdf_file_id"],
            ["file_objects.id"],
            name=op.f("fk_build_records_pdf_file_id_file_objects"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_build_records_project_id_projects"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_build_records")),
        sa.UniqueConstraint(
            "project_id", "version_no", name=op.f("uq_build_records_project_id_version_no")
        ),
    )
    op.create_index(
        "uq_build_records_one_draft",
        "build_records",
        ["project_id"],
        unique=True,
        postgresql_where=sa.text("state = 'DRAFT'"),
    )
    op.create_index(
        "uq_build_records_one_issued",
        "build_records",
        ["project_id"],
        unique=True,
        postgresql_where=sa.text("state = 'ISSUED'"),
    )
    op.create_table(
        "handover_documents",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("handover_id", sa.Uuid(), nullable=False),
        sa.Column("kind", sa.String(length=15), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("file_id", sa.Uuid(), nullable=False),
        sa.Column("added_by", sa.Uuid(), nullable=False),
        sa.Column("added_role", sa.String(length=12), nullable=False),
        sa.Column(
            "added_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.CheckConstraint(
            "kind IN ('WARRANTY', 'MANUAL', 'DRAWING', 'CERTIFICATE', 'PHOTO', 'OTHER')",
            name=op.f("ck_handover_documents_kind"),
        ),
        sa.ForeignKeyConstraint(
            ["added_by"],
            ["users.id"],
            name=op.f("fk_handover_documents_added_by_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["file_id"],
            ["file_objects.id"],
            name=op.f("fk_handover_documents_file_id_file_objects"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["handover_id"],
            ["handovers.id"],
            name=op.f("fk_handover_documents_handover_id_handovers"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_handover_documents")),
        sa.UniqueConstraint(
            "handover_id", "file_id", name=op.f("uq_handover_documents_handover_id_file_id")
        ),
    )
    op.create_table(
        "warranties",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("handover_id", sa.Uuid(), nullable=False),
        sa.Column("item", sa.String(length=200), nullable=False),
        sa.Column("term", sa.String(length=120), nullable=False),
        sa.Column("expiry_date", sa.Date(), nullable=False),
        sa.Column("installer", sa.String(length=200), nullable=False),
        sa.Column("spec_line_code", sa.String(length=3), nullable=True),
        sa.Column("document_id", sa.Uuid(), nullable=True),
        sa.Column("added_by", sa.Uuid(), nullable=False),
        sa.Column(
            "added_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["added_by"],
            ["users.id"],
            name=op.f("fk_warranties_added_by_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["handover_documents.id"],
            name=op.f("fk_warranties_document_id_handover_documents"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["handover_id"],
            ["handovers.id"],
            name=op.f("fk_warranties_handover_id_handovers"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_warranties")),
    )
    # ### end Alembic commands ###
    _upgrade_guards()


def _upgrade_guards() -> None:
    op.execute("ALTER TABLE file_objects DROP CONSTRAINT ck_file_objects_purpose")
    op.execute(
        "ALTER TABLE file_objects ADD CONSTRAINT ck_file_objects_purpose CHECK (purpose IN "
        f"({PURPOSES_BEFORE}, 'HANDOVER_DOCUMENT', 'BUILD_RECORD_DOCUMENT', "
        "'BUILD_RECORD_EXPORT'))"
    )
    op.execute("ALTER TABLE otp_challenges DROP CONSTRAINT ck_otp_challenges_purpose")
    op.execute(
        "ALTER TABLE otp_challenges ADD CONSTRAINT ck_otp_challenges_purpose CHECK (purpose IN "
        f"({OTP_BEFORE}, 'ACKNOWLEDGE_HANDOVER'))"
    )
    op.execute(
        sa.text(
            "INSERT INTO acknowledgement_statements (id, version, text, status, note) "
            "VALUES (CAST(:id AS uuid), 1, :text, 'ACTIVE', :note)"
        ).bindparams(id=STATEMENT_V1_ID, text=STATEMENT_V1, note=STATEMENT_V1_NOTE)
    )
    for table in ("handover_documents", "warranties"):
        op.execute(
            f"CREATE TRIGGER {table}_open_only BEFORE INSERT OR UPDATE OR DELETE ON {table} "
            "FOR EACH ROW EXECUTE FUNCTION p2b_child_editable('handovers', 'handover_id', 'OPEN')"
        )
    # A handover never changes once acknowledged or issued by operations; a Build Record version
    # never changes once issued, except ISSUED to SUPERSEDED.
    op.execute(
        """
        CREATE FUNCTION p2b_records_frozen() RETURNS trigger LANGUAGE plpgsql AS $$
        BEGIN
            IF TG_TABLE_NAME = 'handovers'
               AND OLD.state IN ('ACKNOWLEDGED', 'ISSUED_BY_OPERATIONS') THEN
                RAISE EXCEPTION 'handover % is final', OLD.id;
            END IF;
            IF TG_TABLE_NAME = 'build_records' AND OLD.state = 'SUPERSEDED' THEN
                RAISE EXCEPTION 'build record % is superseded', OLD.id;
            END IF;
            IF TG_TABLE_NAME = 'build_records' AND OLD.state = 'ISSUED' AND (
                NEW.state <> 'SUPERSEDED'
                OR (to_jsonb(NEW) - 'state' - 'version' - 'updated_at')
                   IS DISTINCT FROM (to_jsonb(OLD) - 'state' - 'version' - 'updated_at')
            ) THEN
                RAISE EXCEPTION 'build record % is issued', OLD.id;
            END IF;
            RETURN NEW;
        END $$;
        """
    )
    for table in ("handovers", "build_records"):
        op.execute(
            f"CREATE TRIGGER {table}_frozen BEFORE UPDATE ON {table} "
            "FOR EACH ROW EXECUTE FUNCTION p2b_records_frozen()"
        )
    for table, columns in MUTABLE_COLUMNS.items():
        arguments = ", ".join(f"'{c}'" for c in columns)
        op.execute(
            f"CREATE TRIGGER {table}_lifecycle_only BEFORE UPDATE OR DELETE ON {table} "
            f"FOR EACH ROW EXECUTE FUNCTION p2b_allow_only_columns({arguments})"
        )
    for table in APPEND_ONLY:
        op.execute(
            f"CREATE TRIGGER {table}_append_only BEFORE UPDATE OR DELETE ON {table} "
            "FOR EACH ROW EXECUTE FUNCTION p2b_forbid_mutation()"
        )
    op.execute(
        """
        DO $$
        BEGIN
            IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'app_rw') THEN
                GRANT SELECT, INSERT, UPDATE ON acknowledgement_statements, handovers,
                    build_records TO app_rw;
                GRANT SELECT, INSERT, UPDATE, DELETE ON handover_documents, warranties TO app_rw;
                GRANT SELECT, INSERT ON records_events TO app_rw;
            END IF;
        END $$;
        """
    )


def downgrade() -> None:
    """The feature's tables go (generated commands), then its files and codes (append-only
    guards lifted for exactly these deletes)."""
    for table in ("handovers", "build_records"):
        op.execute(f"DROP TRIGGER {table}_frozen ON {table}")
    op.execute("DROP FUNCTION p2b_records_frozen()")
    _downgrade_tables()
    op.execute("ALTER TABLE document_access_log DISABLE TRIGGER document_access_log_append_only")
    op.execute(
        "DELETE FROM document_access_log WHERE file_id IN (SELECT id FROM file_objects WHERE "
        "purpose IN ('HANDOVER_DOCUMENT', 'BUILD_RECORD_DOCUMENT', 'BUILD_RECORD_EXPORT'))"
    )
    op.execute("ALTER TABLE document_access_log ENABLE TRIGGER document_access_log_append_only")
    op.execute(
        "DELETE FROM file_objects WHERE purpose IN ('HANDOVER_DOCUMENT', "
        "'BUILD_RECORD_DOCUMENT', 'BUILD_RECORD_EXPORT')"
    )
    op.execute("ALTER TABLE file_objects DROP CONSTRAINT ck_file_objects_purpose")
    op.execute(
        "ALTER TABLE file_objects ADD CONSTRAINT ck_file_objects_purpose CHECK (purpose IN "
        f"({PURPOSES_BEFORE}))"
    )
    op.execute("DELETE FROM otp_challenges WHERE purpose = 'ACKNOWLEDGE_HANDOVER'")
    op.execute("ALTER TABLE otp_challenges DROP CONSTRAINT ck_otp_challenges_purpose")
    op.execute(
        "ALTER TABLE otp_challenges ADD CONSTRAINT ck_otp_challenges_purpose CHECK (purpose IN "
        f"({OTP_BEFORE}))"
    )


def _downgrade_tables() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("warranties")
    op.drop_table("handover_documents")
    op.drop_index(
        "uq_build_records_one_issued",
        table_name="build_records",
        postgresql_where=sa.text("state = 'ISSUED'"),
    )
    op.drop_index(
        "uq_build_records_one_draft",
        table_name="build_records",
        postgresql_where=sa.text("state = 'DRAFT'"),
    )
    op.drop_table("build_records")
    op.drop_index("ix_records_events_project", table_name="records_events")
    op.drop_table("records_events")
    op.drop_table("handovers")
    op.drop_index(
        "uq_acknowledgement_statements_one_active",
        table_name="acknowledgement_statements",
        postgresql_where=sa.text("status = 'ACTIVE'"),
    )
    op.drop_table("acknowledgement_statements")
    # ### end Alembic commands ###


PURPOSES_BEFORE = (
    "'REQUIREMENT_UPLOAD', 'AI_CONCEPT', 'VERIFICATION_EVIDENCE', 'PORTFOLIO', 'INVOICE', "
    "'QUOTE_DOCUMENT', 'DRAWING', 'BUILD_PLAN_EVIDENCE', 'BUILD_PLAN_DOCUMENT', "
    "'QUOTE_ATTACHMENT', 'COMPARISON_DOCUMENT', 'STAGE_EVIDENCE', 'INSPECTION_EVIDENCE', "
    "'INSPECTION_REPORT'"
)
OTP_BEFORE = "'LOGIN', 'ACCEPT_BUILD_PLAN', 'SIGN_STRUCTURAL', 'SELECT_QUOTE', 'SUBMIT_INSPECTION'"
STATEMENT_V1_ID = "37000000-0000-7000-8000-000000000101"
STATEMENT_V1 = (
    "I acknowledge that Plan2Build has recorded the handover of project $project_code, with the "
    "documents and warranties listed in the handover record. This acknowledgement confirms only "
    "that I received the handover record. It is not a completion certificate, an approval of the "
    "construction or a statement about its quality, and it does not change my contract with my "
    "contractor."
)
STATEMENT_V1_NOTE = (
    "Functional wording. IMPLEMENTED / PENDING FINAL CLIENT + LEGAL CONFIRMATION (Chirag, "
    "2026-10-06, EX-15); replace with the launch-approved wording as a new version."
)
# Copies of the models' guard lists as they stand in this revision.
MUTABLE_COLUMNS = {
    "acknowledgement_statements": ("status", "activated_by", "activated_at"),
    "handovers": (
        "state", "ready_by", "ready_at", "acknowledged_by", "acknowledged_at", "challenge_id",
        "statement_id", "statement_text", "forced_by", "forced_at", "forced_reason",
        "updated_at", "version",
    ),
    "build_records": (
        "state", "snapshot", "snapshot_sha256", "pdf_file_id", "pdf_sha256", "json_file_id",
        "json_sha256", "issued_by", "issued_at", "updated_at", "version",
    ),
}  # fmt: skip
APPEND_ONLY = ("records_events",)
