"""Concept floor plans, Checkpoint 1 (PD-28, ADR-025; AI_DESIGN_ENGINE_CHECKPOINT_1 section C).

Revision ID: 0019
Revises: 0018
Create Date: 2026-10-06

Additive only (rung M1): `layout_rulesets` (versioned rules; content immutable; one PUBLISHED; a
synthetic ruleset can never be approved or published), `house_plans` (one generation and its
working head; VALID is the only state with a document; never authoritative; one generation in
flight per project) and `house_plan_versions` (append-only snapshots). No seed data: no ruleset
row is created here (AD-05). The operation-history table waits for the editing checkpoint (CP1-11).
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0019"
down_revision: str | None = "0018"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "layout_rulesets",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=10), nullable=False),
        sa.Column("is_synthetic", sa.Boolean(), nullable=False),
        sa.Column("schema_version", sa.String(length=16), nullable=False),
        sa.Column("content", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("content_sha256", sa.String(length=64), nullable=False),
        sa.Column("note", sa.Text(), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("approved_by", sa.Uuid(), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("published_by", sa.Uuid(), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("retired_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "(content ->> 'synthetic')::boolean = is_synthetic",
            name=op.f("ck_layout_rulesets_synthetic_matches_content"),
        ),
        sa.CheckConstraint(
            "NOT (is_synthetic AND status IN ('APPROVED', 'PUBLISHED'))",
            name=op.f("ck_layout_rulesets_synthetic_never_approved"),
        ),
        sa.CheckConstraint(
            "status <> 'PUBLISHED' OR published_by IS NOT NULL",
            name=op.f("ck_layout_rulesets_publication_named"),
        ),
        sa.CheckConstraint(
            "status IN ('DRAFT', 'APPROVED', 'PUBLISHED', 'RETIRED')",
            name=op.f("ck_layout_rulesets_status"),
        ),
        sa.CheckConstraint(
            "status NOT IN ('APPROVED', 'PUBLISHED', 'RETIRED') OR approved_by IS NOT NULL",
            name=op.f("ck_layout_rulesets_approval_named"),
        ),
        sa.ForeignKeyConstraint(
            ["approved_by"],
            ["users.id"],
            name=op.f("fk_layout_rulesets_approved_by_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_layout_rulesets_created_by_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["published_by"],
            ["users.id"],
            name=op.f("fk_layout_rulesets_published_by_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_layout_rulesets")),
        sa.UniqueConstraint("version", name=op.f("uq_layout_rulesets_version")),
    )
    op.create_index(
        "uq_layout_rulesets_one_published",
        "layout_rulesets",
        ["status"],
        unique=True,
        postgresql_where=sa.text("status = 'PUBLISHED'"),
    )
    op.create_table(
        "house_plans",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("state", sa.String(length=12), nullable=False),
        sa.Column("design_inputs", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("intent", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("intent_sha256", sa.String(length=64), nullable=False),
        sa.Column("question_set_version", sa.Integer(), nullable=False),
        sa.Column("requirement_version", sa.Integer(), nullable=False),
        sa.Column("ruleset_id", sa.Uuid(), nullable=False),
        sa.Column("ruleset_version", sa.Integer(), nullable=False),
        sa.Column("engine_version", sa.String(length=20), nullable=False),
        sa.Column("solver", sa.String(length=20), nullable=False),
        sa.Column("seed", sa.BigInteger(), nullable=False),
        sa.Column("head_revision_no", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("head_document", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("head_validity", sa.String(length=8), nullable=True),
        sa.Column("head_report", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("infeasibility", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("failure_reason", sa.String(length=32), nullable=True),
        sa.Column("failure_detail", sa.Text(), nullable=True),
        sa.Column("solve_ms", sa.Integer(), nullable=True),
        sa.Column("attempts", sa.SmallInteger(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "is_authoritative", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("requested_by", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.CheckConstraint(
            "(state = 'FAILED') = (failure_reason IS NOT NULL)",
            name=op.f("ck_house_plans_reason_iff_failed"),
        ),
        sa.CheckConstraint(
            "(state = 'INFEASIBLE') = (infeasibility IS NOT NULL)",
            name=op.f("ck_house_plans_reasons_iff_infeasible"),
        ),
        sa.CheckConstraint(
            "(state = 'VALID') = (head_document IS NOT NULL)",
            name=op.f("ck_house_plans_document_iff_valid"),
        ),
        sa.CheckConstraint(
            "failure_reason IS NULL OR failure_reason IN ('ENGINE_ERROR', 'ENGINE_INVALID_OUTPUT', 'ENGINE_TIMEOUT', 'STALE')",
            name=op.f("ck_house_plans_failure_reason"),
        ),
        sa.CheckConstraint(
            "head_validity IS NULL OR head_validity IN ('VALID', 'INVALID')",
            name=op.f("ck_house_plans_head_validity"),
        ),
        sa.CheckConstraint(
            "state IN ('QUEUED', 'RUNNING', 'VALID', 'INFEASIBLE', 'FAILED')",
            name=op.f("ck_house_plans_state"),
        ),
        sa.CheckConstraint(
            "(head_document IS NULL) = (head_report IS NULL)",
            name=op.f("ck_house_plans_report_with_document"),
        ),
        sa.CheckConstraint(
            "(head_document IS NULL) = (head_validity IS NULL)",
            name=op.f("ck_house_plans_validity_with_document"),
        ),
        sa.CheckConstraint(
            "is_authoritative = false", name=op.f("ck_house_plans_never_authoritative")
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_house_plans_project_id_projects"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["requested_by"],
            ["users.id"],
            name=op.f("fk_house_plans_requested_by_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["ruleset_id"],
            ["layout_rulesets.id"],
            name=op.f("fk_house_plans_ruleset_id_layout_rulesets"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_house_plans")),
        sa.UniqueConstraint(
            "project_id", "sequence", name=op.f("uq_house_plans_project_id_sequence")
        ),
    )
    op.create_index(
        "ix_house_plans_project_id_state", "house_plans", ["project_id", "state"], unique=False
    )
    op.create_index(
        "uq_house_plans_one_in_flight",
        "house_plans",
        ["project_id"],
        unique=True,
        postgresql_where=sa.text("state IN ('QUEUED', 'RUNNING')"),
    )
    op.create_table(
        "house_plan_versions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("plan_id", sa.Uuid(), nullable=False),
        sa.Column("version_no", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("revision_no", sa.Integer(), nullable=False),
        sa.Column("schema_version", sa.String(length=16), nullable=False),
        sa.Column("document", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("content_sha256", sa.String(length=64), nullable=False),
        sa.Column("validity", sa.String(length=8), nullable=False),
        sa.Column("report", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "validity IN ('VALID', 'INVALID')", name=op.f("ck_house_plan_versions_validity")
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_house_plan_versions_created_by_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["plan_id"],
            ["house_plans.id"],
            name=op.f("fk_house_plan_versions_plan_id_house_plans"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_house_plan_versions")),
        sa.UniqueConstraint(
            "plan_id", "version_no", name=op.f("uq_house_plan_versions_plan_id_version_no")
        ),
    )
    # ### end Alembic commands ###
    _upgrade_guards()


# Copies of the models' guard lists as they stand in this revision.
MUTABLE_COLUMNS = {
    "layout_rulesets": ("status", "approved_by", "approved_at", "published_by", "published_at",
                        "retired_at"),
    "house_plans": ("state", "started_at", "completed_at", "head_revision_no", "head_document",
                    "head_validity", "head_report", "infeasibility", "failure_reason", "failure_detail",
                    "solve_ms", "attempts", "version"),
}  # fmt: skip
APPEND_ONLY = ("house_plan_versions",)


def _upgrade_guards() -> None:
    for table, columns in MUTABLE_COLUMNS.items():
        arguments = ", ".join(f"'{c}'" for c in columns)
        op.execute(
            f"CREATE TRIGGER {table}_lifecycle_only BEFORE UPDATE OR DELETE ON {table} "
            f"FOR EACH ROW EXECUTE FUNCTION p2b_allow_only_columns({arguments})"
        )
    for table in APPEND_ONLY:
        op.execute(
            f"CREATE TRIGGER {table}_append_only BEFORE UPDATE OR DELETE ON {table} "
            "FOR EACH ROW EXECUTE FUNCTION p2b_forbid_mutation()"
        )
    op.execute(
        """
        DO $$
        BEGIN
            IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'app_rw') THEN
                GRANT SELECT, INSERT, UPDATE ON layout_rulesets, house_plans TO app_rw;
                GRANT SELECT, INSERT ON house_plan_versions TO app_rw;
            END IF;
        END $$;
        """
    )


def downgrade() -> None:
    """The three tables go with their triggers; nothing outside them was changed."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("house_plan_versions")
    op.drop_index(
        "uq_house_plans_one_in_flight",
        table_name="house_plans",
        postgresql_where=sa.text("state IN ('QUEUED', 'RUNNING')"),
    )
    op.drop_index("ix_house_plans_project_id_state", table_name="house_plans")
    op.drop_table("house_plans")
    op.drop_index(
        "uq_layout_rulesets_one_published",
        table_name="layout_rulesets",
        postgresql_where=sa.text("status = 'PUBLISHED'"),
    )
    op.drop_table("layout_rulesets")
    # ### end Alembic commands ###
