"""Export the API contract for the web app (ADR-019; API_ARCHITECTURE section 20).

Writes packages/contracts/openapi.json and packages/contracts/src/vocabulary.ts. CI regenerates both
and fails if the committed files differ, so the web app can never drift from the API.
Run from apps/api: `uv run python scripts/export_contracts.py`.
"""

import json
import os
from pathlib import Path

# The schema does not depend on real settings; placeholders let the app build without a database.
for key, value in {
    "P2B_ENV": "test",
    "P2B_DATABASE_URL": "postgresql+asyncpg://contracts:unused@localhost/unused",
    "P2B_HOST_IHB": "plan2build.in",
    "P2B_HOST_PRO": "professionals.plan2build.in",
    "P2B_HOST_OPS": "admin.plan2build.in",
    "P2B_OTP_PEPPER": "unused",
    "P2B_IDENTIFIER_PEPPER": "unused",
    "P2B_ENCRYPTION_KEY": "dW51c2VkLXVudXNlZC11bnVzZWQtdW51c2VkLXVudXM=",
    "P2B_EMAIL_PROVIDER": "memory",
    "P2B_STORAGE_PROVIDER": "memory",
    "P2B_SCANNER_PROVIDER": "accept_all",
    "P2B_GEOCODER_PROVIDER": "none",
    # The fake gateway, so the contract also types the development checkout route that local
    # development and the end-to-end tests use; that route exists nowhere else.
    "P2B_PAYMENT_PROVIDER": "fake",
    "P2B_PAYMENT_KEY_ID": "unused",
    "P2B_PAYMENT_KEY_SECRET": "unused",
    "P2B_PAYMENT_WEBHOOK_SECRET": "unused",
}.items():
    os.environ.setdefault(key, value)

from p2b.core.vocabulary import ALL_ENUMS  # noqa: E402
from p2b.main import create_app  # noqa: E402

CONTRACTS = Path(__file__).resolve().parents[3] / "packages" / "contracts"


def vocabulary_ts() -> str:
    lines = [
        "// Generated by apps/api/scripts/export_contracts.py from p2b/core/vocabulary.py.",
        "// Do not edit by hand.",
        "",
    ]
    for enum in ALL_ENUMS:
        values = ", ".join(json.dumps(member.value) for member in enum)
        lines += [
            f"export const {enum.__name__}Values = [{values}] as const;",
            f"export type {enum.__name__} = (typeof {enum.__name__}Values)[number];",
            "",
        ]
    return "\n".join(lines)


def main() -> None:
    schema = create_app().openapi()
    (CONTRACTS / "openapi.json").write_text(
        json.dumps(schema, indent=2, sort_keys=True) + "\n", encoding="utf-8", newline="\n"
    )
    (CONTRACTS / "src" / "vocabulary.ts").write_text(
        vocabulary_ts(), encoding="utf-8", newline="\n"
    )


if __name__ == "__main__":
    main()
